### ISSUE TITLE
Bug: index out of range due to leading whitespace

### ISSUE THREAD

**Issue by rickb777** [tdewolff/canvas#100]
In text.go line 189 `NewTextBox`, if the string `s` has leading spaces, an index-out-of-range panic occurs.

```
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/tdewolff/canvas.(*RichText).ToText(0xc001009978, 0x4067c00000000000, 0x0, 0x2, 0x3, 0x0, 0x0, 0x30)
        /home/rick/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20210617165953-197132c95069/text.go:492 +0x2d50
github.com/tdewolff/canvas.NewTextBox(0xc000026e00, 0xc0000e2780, 0x21, 0x4067c00000000000, 0x0, 0x2, 0x3, 0x0, 0x0, 0xc000387a48)
        /home/rick/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20210617165953-197132c95069/text.go:192 +0x205
```

I would expect either

1. the index out of range issue is fixed; or
2. the string is left-trimmed in `NewTextBox` (could this give unexpected results?); or
3. a panic is thrown if the string has leading spaces, and it includes an explanation that this is disallowed; or
4. this behaviour is documented and callers must beware.

**Comment by tdewolff** [comment]
Thank you for the 100th bug report ;-), should be fixed now. The space is ignored.
