### ISSUE TITLE
Richtext: Linebreak not working on right aligned Text

### ISSUE THREAD

**Issue by Xyaren** [tdewolff/canvas#102]
Updating to the latest version does not allow me to create Richtext with right-aligned text where each line is aligned to the right, while maintaining automatic line breaks.

Text Input (Each line different font Size, using \n as a manual linebreak): 
```
Fels der Weissagung [FR]
+ Jademeer [FR]
```

```golang
maxWidth := float64(105)
rowSize := float64(40)

[...].ToText(maxWidth, rowSize, canvas.Right, canvas.Center, 0, 0)
```

Before Updating: 
![image](https://user-images.githubusercontent.com/5864045/126370162-85aa3762-cc3f-4444-8a6c-089c1c5d19c4.png)

After Updating:
![image](https://user-images.githubusercontent.com/5864045/126371399-1e209f4f-144d-41af-b275-06894d99b8ca.png)

You can see, that linebreaks are not beeing applied, and the text is over the maximum width.
Maxiumum width is equal to the green boxes width, while the red box indicates the canvas.Text resulting Bound.

Please advice, how to align it like it was before updating.

Possible breaking commit: https://github.com/tdewolff/canvas/commit/386f4f513035f7744bd63e54e771f34aec07e561

I hope you can help me with that :)

**Comment by Xyaren** [comment]
Example Code that shows, that bounds are not recognized at all:
```golang
func main() {
	var colorGreen = color.RGBA{R: 94, G: 185, B: 94, A: 255}
	//var colorBlue = color.RGBA{R: 14, G: 144, B: 210, A: 255}
	var colorRed = color.RGBA{R: 221, G: 81, B: 76, A: 255}

	result := canvas.New(200, 200)
	ctx := canvas.NewContext(result)

	fontFamily := canvas.NewFontFamily("times")
	_ = fontFamily.LoadLocalFont("times", canvas.FontRegular)

	standardFace := fontFamily.Face(35.0, canvas.White, canvas.FontRegular, canvas.FontNormal)
	secondaryFace := fontFamily.Face(25.0, canvas.White, canvas.FontRegular, canvas.FontNormal)

	richText := canvas.NewRichText(standardFace)
	richText.Add(standardFace, "Fels der Weissagung [FR]")
	richText.Add(secondaryFace, "\n + Jademeer [FR]")

	const maxWidth = 75
	const maxHeight = 100
	text := richText.ToText(maxWidth, maxHeight, canvas.Right, canvas.Center, 0, 0)
	ctx.DrawText(100-text.Bounds().X-text.Bounds().W/2, 100-text.Bounds().Y-text.Bounds().H/2, text)

	ctx.SetStrokeColor(colorRed)
	ctx.SetFillColor(canvas.Transparent)
	ctx.DrawPath(100-text.Bounds().W/2,100-text.Bounds().H/2,canvas.Rectangle(text.Bounds().W,text.Bounds().H))

	//Red Box: Actual Bounds
	ctx.SetStrokeColor(colorRed)
	ctx.SetFillColor(canvas.Transparent)
	ctx.DrawPath(100-text.Bounds().W/2,100-text.Bounds().H/2,canvas.Rectangle(text.Bounds().W,text.Bounds().H))


	//Green Box, supplied bounds
	ctx.SetStrokeColor(colorGreen)
	ctx.SetFillColor(canvas.Transparent)
	ctx.DrawPath(100-maxWidth/2,100-maxHeight/2,canvas.Rectangle(maxWidth,maxHeight))

	_ = renderers.Write("out.jpeg", result, canvas.DPMM(2))
}
```
Output:
![out](https://user-images.githubusercontent.com/5864045/126376270-583a04f3-228a-4079-b7d0-ae0b84144cdb.jpeg)

**Comment by Xyaren** [comment]
Setting text.go:351 to "Justifyied" will result in the desired result !?
### Change in text.go
![image](https://user-images.githubusercontent.com/5864045/126811482-cae65a90-8b08-494b-be57-3152cb081b7e.png)

### Call:
```golang
	text := richText.ToText(maxWidth, maxHeight, canvas.Right, canvas.Center, 0, 0)
```
### Result
![out](https://user-images.githubusercontent.com/5864045/126811326-66f34642-97dd-4706-91ee-7a83787c5393.jpeg)

I'm not sure what that will break, so not creating a PR.

**Comment by tdewolff** [comment]
There are three algorithms for line breaking, one for left aligned (and right), one for centered, and one for justified text. The algorithms are very similar but have minor differences that fit their goal. E.g. for centered text a line that it sticking out is half as bad as the same line sticking out for left/right aligned text, just because the sticking out part gets divided over the left and right in the case of centered text. The differences are very minor, so to fix this issue I've fixed it to the justified algorithm. The line breaking should be fixed for left/right aligned text, as well as centered text, in the future. Thanks for the great analysis!

**Comment by tdewolff** [comment]
Actually, this is a bad fix. This bug needs to be investigated more to see why the proposed line breaks around "Weissagung" are being rejected. Unfortunately I count with very little time at my disposal at the moment...

**Comment by Xyaren** [comment]
Thank you for the analysis.
I'm looking forward to see this getting solved, once you find time for it :)

**Comment by tdewolff** [comment]
I've added a commit that fixes a number of subtle problems, including yours. Please check and let me know how it goes!

**Comment by Xyaren** [comment]
Works fine :)
