### ISSUE TITLE
panic: cmap: bad idRangeOffset in subtable 0

### ISSUE THREAD

**Issue by zostay** [tdewolff/canvas#106]
I think there's a problem in the font parsing code related to glyph subtables. It's too late in the evening for me to try to diagnose this further. I hope to make time to look into this more this weekend. What I can say is that I can't load the [Magic School One](https://www.fontspace.com/magic-school-font-f3161) font using the following code:

```go	
        fam := canvas.NewFontFamily("MagicSchoolOne")
	fontBytes := MustAsset("MagicSchoolOne.ttf")

	err := fam.LoadFont(fontBytes, 0, canvas.FontRegular)
	if err != nil {
		panic(err)
	}

	MagicSchoolOne = fam.Face(160, canvas.Black, canvas.FontRegular, canvas.FontNormal)
```

(I am loading the font into Go code using `go-bindata`, so `MustAsset` is just the bytes of the file after it has been read into into a byte slice.) The above code panics with the error:

```panic: cmap: bad idRangeOffset in subtable 0```

Hopefully I can *delve* into this tomorrow with the debugger.

One note of confusion, that error message appears twice in the source code, which leads to an ambiguity: Which error is triggering the problem? In this case, the value would trigger both errors if it could. The value of `idRangeOffset` is 65535, which is not an even number (first error), and if it got past that, it's greater than the value of `glyphIdArrayLength`, 232 (second error).

**Comment by zostay** [comment]
I found that I was out of my depth and lacking enough knowledge of SFNT to do anything useful. I found a work-around instead, which is to load the font into FontForge and regenerate it as a fresh TTF. This cleaned it up enough to make it usable for my purpose.

**Comment by tdewolff** [comment]
Thanks for the bug report! The last value in the cmap format 4 subtable should have start and end code 0xFFFF, but the delta and offset values could be invalid (as is the case for the mentioned font). I've fixed it in the commit above, let me know if that works well for you!
