### ISSUE TITLE
Collection of documentation upgrade requests

### ISSUE THREAD

**Issue by yarbelk** [tdewolff/canvas#109]
Some constants and types are basically magic numbers and could do with clearer documentation.

```
const (
	// CartesianI is the top left quadrent
	CartesianI CoordSystem = iota
	// CartesianII is ...
	CartesianII
	CartesianIII
	CartesianIV
)
```

Some types also expect knowledge that may be too specialized to expect someone to know coming in.  I know there are things here that I learned 10+years ago, but have absolutely forgotten.  It may be nice to at least temporally link out to a wiki page or something for some of them, at least until there can be a ELIF like doc written (which is hard to do).

- [x] CartesianI - IV
- [x] GammaColorSpace
- [x] LinearColorSpace (link out to linear RGB doc may be enough)
- [x] Everything where affine transforms are mentioned; even knowing what an affine transform, a couple examples about how transform, rotate, skew impacts things like DrawText.  It is also slightly confusing, because DrawPath has the line `DrawPath draws a path at position (x,y) using the current draw state. ` and DrawText has `DrawText draws text at position (x,y) using the current draw state. In particular, it uses only the current affine transformation matrix. `  : what is the draw state difference between the two? the documentation expects an understanding of a full concept and its partial negation (Subtractive Documentation maybe, vs Additive Documentation?  manufacturing metaphor)
- [x] ZIndex - how do they work w.r.t Canvas vs. Context?

**Comment by tdewolff** [comment]
Thanks for the issue! I agree completely with your observation, I've improved some of the points, please let me know if you feel that it is explained clearly or whether it could be improved more still. Thanks!

**Comment by yarbelk** [comment]
Much clearer; and it seems i misunderstood some stuff; so it has already helped me!
