### ISSUE TITLE
Add grayscale colorspace

### ISSUE THREAD

**Issue by yarbelk** [tdewolff/canvas#110]
Sometimes you want black and white.  Sometimes you have 16 shades to work with. sometimes you have 2.  sometimes more.  My color theory is not good enough to know a good algorithm for this (I know you need to take RGB colors weighted by some factor of eye sensitivity etc).

**Comment by tdewolff** [comment]
True, well maybe the naming isn't ideal. While linear and sRGB are color spaces, this is really only useful for gamma-correction and not for grayscale conversion. I agree that such a conversion would be handy though, but it'd be another separate feature. I may rename the current color spaces to reflect their function better, any advice always welcome! What about "GammaCorrector"?

**Comment by yarbelk** [comment]
From my reading of what it does now; I think that is clearer.  That said I haven't don any serious colourspace stuff in 7 years (which wasn't much to begin with) and was print CYMK stuff; which is its own barrel of crazy.

For my use cases (which basically involves blitting changes to epaper), i may add the transaltion on the final stage on a per-device level.  Eg, if its 2 bit (BW), 3-bit (BW + Red or Yellow), 4 bit (16 grey) etc.  in these cases the exact 'color' representation is display specific, so it makes sense to happen right at the end while keeping the intermediate layering and composition in a consistent space.

**Comment by tdewolff** [comment]
That is absolutely a useful feature which I can implemented in two ways: a Filter struct between Context and a renderer that converts colors. You can draw to Canvas and then redraw to your final target passing through that filter. Otherwise, implement in the renderer itself if this is very renderer specific. What render target do you use? The rasterizer? You can use the rasterizer to draw to `image.Image` and then use another library to convert that to different color palettes, that might be the best way.

**Comment by yarbelk** [comment]
My plan was rasterizer -> `image.Image` -> change colour space -> low level outputs; in my case, its SPI (https://en.wikipedia.org/wiki/Serial_Peripheral_Interface).

I'm _super_ happy you updated the docs because that article on gamma is really, really helpful.  I need to investigate the gamma corrections for the e-paper displays I'm targeting.  This is something I never considered.

**Comment by tdewolff** [comment]
To close this issue, I think that color space is the correct name, even though it only treats gamma correction color spaces. The specific requested functionality is best implemented as you said: rasterizer to an image and from there you can convert it to grayscale however you like. Happy to answer other questions!
