### ISSUE TITLE
Gio RTL / LTR questions …

### ISSUE THREAD

**Issue by gedw99** [tdewolff/canvas#112]
I have time to work on getting gio support for multiple languages as well as RTL / LTR.

I could not see any multi directional examples in the examples folder for any of the go gui frameworks , so figured it’s worth asking first if perhaps there is other work required to start to build gio gui that shows off multi directional text.

My aim is to abstract it as much as possible so that a developer does not have to change their layout code but I expect that will require changing the code in gio framework itself. So I figured it’s work starting at a higher level in your repo to get the feel for it.

thanks for this fantastic repo btw. It’s so needed in the community.

I have i18n multi language working with gio btw. It’s using the standard lib that gives full workflow. Namely 
https://github.com/nicksnyder/go-i18n. Hence why I want to try to get multi direction layout and text working with gio. Wil submit to gio repo when it’s ready.

**Comment by tdewolff** [comment]
Hi @gedw99 , thanks for the interest! To give you a quick summary of the text support in this library: in `text.go` the `RichText` structure is what supports using multiple fonts in one text area (including RTL/LTR), as well as the formatting and placement of the words according to Donald Knuth's algorithm. It works as follows: re-ordering for drawing from left-to-right using FriBidi, itemizations of the text by splitting per font face and script, shaping the text into a list of glyphs, convert these glyphs into items for the line breaking algorithm. From there we start drawing the text line per line, backing up through all the conversions mentioned until we have text spans at certain positions consisting of a list of glyphs and the text it represents.

Within `text/` there are several functionalities: FriBidi for support LTR/RTL mixing of text, HarfBuzz for text shaping, and linebreak for the line breaking algorithm. Please see https://github.com/tdewolff/canvas/blob/master/examples/gio/main.go for an example of using the Gio renderer with RTL/LTR mixed text (you can see Russian and Arabic being mixed on one line). Please let me know if you have any more questions!

**Comment by gedw99** [comment]
Thanks for explanation 

I have to look up that also. I always wondered how it worked. 👍 

more questions : 

should be abstract it so it works with all render engines you support ?

**Comment by tdewolff** [comment]
Not sure I understand, the `Text` package and all its functionality is completely render target independent.

**Comment by gedw99** [comment]
Ok well that answers my question. 
Nice...

will work on the i18n package....

**Comment by gedw99** [comment]
@tdewolff 

I have been working on i18n aspects in various ways and am just swinging back to this..

The example you gave at https://github.com/tdewolff/canvas/blob/master/examples/gio/main.go intermixes the text as you said. 

Am working on whole screen being flipped between RTL and LTR with gio.
Example: https://phrase.com/blog/wp-content/uploads/2018/07/react-native-i18n-15.png
