### ISSUE TITLE
Supporting SEO to keep the SEO gods happy

### ISSUE THREAD

**Issue by gedw99** [tdewolff/canvas#113]
I love using gio for apps but want public pages to get SEO 

1. output meta tags ? 

2, detect their spider and pump out a html canvas just for them ?

3. Other ??

1 is better than nothing and easy to do from gio wasm to the Dom meta tags . But it’s limited to small pages.

this relies on the gio router responding to URLs sent it it . Currently is does not but that can be fixed.

2 . Imho it’s a big no with the search engines to do a switch of content based on if it’s a spider or not .

would be cool to see if others have a concept / approach on this

**Comment by tdewolff** [comment]
I'm not following what you try to communicate. Gio has nothing to do with HTML Canvas, they are different render targets. Please look at https://github.com/tdewolff/canvas/blob/master/examples/html-canvas/index.html to see an example of how to use the HTML Canvas target. That HTML page is what you write yourself, embedding the HTML Canvas. If you want to add SEO stuff, this has nothing to do with HTML Canvas.

**Comment by tdewolff** [comment]
Please reopen & clarify if this remains a problem!

**Comment by gedw99** [comment]
sorry that i did not get back to you on this one. Saw it but got side tracked.

I wrote up a proposal here to get the ball rolling: https://github.com/gedw99/gio-proposals/tree/main/seo

Points to note are that it includes Actions, like hyperlinks working etc.
I feel bad about needing a SDL to do it, but cant see another way right now... 

If you have any brain waves on it please feel free to make an issue etc.
