### ISSUE TITLE
Go-chart pie chart PDF mis-rendering

### ISSUE THREAD

**Issue by dblueman** [tdewolff/canvas#115]
When adjusting the go-charts pie chart example [1] (see output.png) to use the excellent canvas PDF rendering [2], the output is misrendered (see output.pdf).

[1] https://github.com/wcharczuk/go-chart/blob/master/examples/pie_chart/main.go

-- [2]

```
package main

import (
	"os"

	"github.com/tdewolff/canvas/renderers"
	"github.com/wcharczuk/go-chart/v2"
)

func main() {
	pie := chart.PieChart{
		Width:  512,
		Height: 512,
		Values: []chart.Value{
			{Value: 5, Label: "Blue"},
			{Value: 5, Label: "Green"},
			{Value: 4, Label: "Gray"},
			{Value: 4, Label: "Orange"},
			{Value: 3, Label: "Deep Blue"},
			{Value: 3, Label: "??"},
			{Value: 1, Label: "!!"},
		},
	}

	f, _ := os.Create("output.pdf")
	defer f.Close()

	pie.Render(renderers.NewGoChart(renderers.PDF()), f)
}
```

![output](https://user-images.githubusercontent.com/2580948/132282532-63956068-6d23-48b4-a2d5-39237f8a70b4.png)
[output.pdf](https://github.com/tdewolff/canvas/files/7118802/output.pdf)

**Comment by tdewolff** [comment]
Thanks for the bug report, I'll look into it!

**Comment by tdewolff** [comment]
I've added a fix, please let me know if you have any other problems

**Comment by dblueman** [comment]
Superb fix! Tests out well with more complex pie charts.
