### ISSUE TITLE
 how to set font Stroke？

### ISSUE THREAD

**Issue by xiusin** [tdewolff/canvas#116]

**Comment by tdewolff** [comment]
Is the question, how can I draw a stroke around text contours? You'll need to convert your `Text` to a `Path` (using `text.ToPath()`) and use that to draw it as a stroke. There is no internal support yet for stroked text within the `Text` functionality. Stroking and shadow are two features in consideration.

**Comment by xiusin** [comment]
@tdewolff My English is not very good. That's roughly what I mean. Thank you
