### ISSUE TITLE
How to reset the startPoint(0,0) to the left-top of screen?

### ISSUE THREAD

**Issue by luankefei** [tdewolff/canvas#14]
same as title

**Comment by tdewolff** [comment]
I'm working on an easy transformations for passed coordinates. To be clear: you want a call to `c.DrawPath(5, 5, path)` to be drawn at `(5,5)` from the top-left corner. In other words, the `path` is not to be flipped vertically?
If you _do_ want the latter, take a look at using a view on a canvas.
