### ISSUE TITLE
Does tdewolff/canvas currently work with go get?

### ISSUE THREAD

**Issue by carbocation** [tdewolff/canvas#150]
What I ran:
```sh
go get -u github.com/tdewolff/canvas
```

What it fetched:
```sh
go: downloading github.com/tdewolff/canvas v0.0.0-20220113195210-2b774ce29caa
go: downloading github.com/ByteArena/poly2tri-go v0.0.0-20170716161910-d102ad91854f
go: downloading github.com/go-latex/latex v0.0.0-20210823091927-c0d11ff05a81
go: downloading github.com/adrg/sysfont v0.1.2
go: downloading github.com/tdewolff/minify/v2 v2.9.26
go: downloading github.com/tdewolff/parse/v2 v2.5.26
go: downloading github.com/benoitkugler/textlayout v0.0.3
go: downloading github.com/tdewolff/parse/v2 v2.5.27
go: downloading github.com/tdewolff/parse v1.1.0
go: downloading github.com/dsnet/compress v0.0.1
go: downloading github.com/tdewolff/minify v1.1.0
go: downloading github.com/tdewolff/minify/v2 v2.10.0
go: downloading github.com/adrg/strutil v0.2.2
go: downloading github.com/adrg/xdg v0.4.0
go: downloading github.com/adrg/strutil v0.2.3
go: downloading golang.org/x/sys v0.0.0-20220209214540-3681064d5158
go: downloading github.com/benoitkugler/textlayout v0.0.9
go: downloading golang.org/x/exp v0.0.0-20210722180016-6781d3edade3
go: downloading gonum.org/v1/gonum v0.9.3
go: added github.com/adrg/strutil v0.2.3
go: added github.com/benoitkugler/textlayout v0.0.9
go: added github.com/tdewolff/canvas v0.0.0-20220113195210-2b774ce29caa
go: added github.com/tdewolff/minify/v2 v2.10.0
go: upgraded golang.org/x/sys v0.0.0-20211007075335-d3039528d8ac => v0.0.0-20220209214540-3681064d5158
go: upgraded gonum.org/v1/gonum v0.8.2 => v0.9.3
```

But then trying to run code including `github.com/tdewolff/canvas`, I get compile-time errors:
```sh
/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20220113195210-2b774ce29caa/text/harfbuzz.go:23:50: too many arguments in call to truetype.Parse
        have (*bytes.Reader, bool)
        want (fonts.Resource)
```

**Comment by carbocation** [comment]
Seems to have been introduced recently in 2b774ce [specific link](https://github.com/tdewolff/canvas/commit/2b774ce29caa883ca60b59a14dd58b763d5c00fc#diff-1764079db4f83167d1bbb3548265e5b14c5af19e37d3709288058454d2ed7770L23)

**Comment by carbocation** [comment]
Confirmed that downgrading by one commit to go get ed6dd6946a4329e08f6c606c8349003b573419d7 resolved this for me. (For purposes of `go get`, this is `go get github.com/tdewolff/canvas@ed6dd6946a4329e08f6c606c8349003b573419d7`)

**Comment by carbocation** [comment]
On further inspection, this seems to be because my `go.mod` requires a subsequent version of that library, and it seems to have had a non-Semvar breaking change to the public API between v0.0.3 and v0.0.9. I am a little surprised go.mod didn't handle that automatically. But at any rate, this doesn't seem to be a canvas-specific issue from what I can see.

**Comment by tdewolff** [comment]
Yes, I had the same problem which is why I pushed out the commit to fix the function call. Does this cause a problem for new users? Or only for people upgrading `canvas` but not `textlayout`?

**Comment by carbocation** [comment]
I happened to be a new user whose project already incorporated the later (v0.0.9) `textlayout`. So yes I think that combo is what is required to reproduce the issue.

I believe the commit ( 2b774ce29caa883ca60b59a14dd58b763d5c00fc , specific [link here](https://github.com/tdewolff/canvas/commit/2b774ce29caa883ca60b59a14dd58b763d5c00fc#diff-1764079db4f83167d1bbb3548265e5b14c5af19e37d3709288058454d2ed7770L23) ) makes sense as long as v0.0.3 is kept (it breaks compatibility with v0.0.9).

I also created a new repo that points to tdewolff/canvas and didn't have this issue.

Not clear that there is anything to be done here (unless you plan to upgrade the `textlayout` version to v0.0.9), but hopefully this is useful for other people who may fall into the same boat that I did due to having textlayout v0.0.9.

Ultimately I think this is an issue with textlayout changing their public API without following SemVer.

**Comment by MrDOS** [comment]
> Ultimately I think this is an issue with textlayout changing their public API without following SemVer.

To interject with a Friday afternoon dose of pedantism, [they are following SemVer](https://semver.org/#spec-item-4):

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by carbocation** [comment]
Pedantry is welcome, and I stand corrected.
