### ISSUE TITLE
Figure 1. in the README appears to be broken

### ISSUE THREAD

**Issue by aldernero** [tdewolff/canvas#153]
I visited the repo for the first time today, and I don't see an image for Figure 1. Clicking on the link, [https://raw.githubusercontent.com/tdewolff/canvas/master/resources/preview/preview.png](https://raw.githubusercontent.com/tdewolff/canvas/master/resources/preview/preview.png), just brings up a blank page.

**Comment by tdewolff** [comment]
Thanks, this has now been fixed, sorry for the delay
