### ISSUE TITLE
Concurrent access to map in font.go

### ISSUE THREAD

**Issue by rickb777** [tdewolff/canvas#155]
`Font.SubsetID()` uses `subsetIDMap map[uint16]uint16` (font.go:126).

Concurrent access to maps is disallowed and the race detector highlights this.

Because `Font` is always accessed through a pointer, it is possible to have rendering issues if multiple goroutines are trying to render separate PDF documents at the same time, when the same font is used for the text.

I noticed this in renderers/pdf/writer.go:849

Typically, what happens is that the rendering works correctly provided that the first goroutine that invokes `Font.SubsetID()` does so without clashing with any other goroutines using the same `Font`. Subsequent calls will also succeed because the tendency is to have concurrent cache hits on that `subsetIDMap`.

From time to time, but very rarely, a stack trace arises in production because an actual clash happened.

#### Suggestions

The simple solution is to use a sync.Mutex within `Fond.SubsetID`, but because this method is used within loops, it might not be fast enough to acquire and release the lock on every call. A different API that handles multiple glyph IDs in a batch would mitigate this

One possible lock-free solution might be to do away with the map and just keep the slice `subsetIDs []uint16`. Finding an existing subset ID would need a linear search through this; however it would be relatively quick because the values are integers so equality comparisons are fast. Adding to the slice would require an `atomic.Value` swap of the new slice for the old slice.

That said, `Font.SubsetID()` is called within loops so its performance probably matters.

Another solution might be through `sync.Map`, although there would then be a need for interface pointers around every glyph ID (keys and values), so this might possibly work out slower than linear searching.

(There may be better solutions.)

#### Testing

Unfortunately, there don't seem to be unit tests for this part of the font code, nor for the PDF renderer.

**Comment by tdewolff** [comment]
Thank you so much for the great and deep analysis of the problem. The subset structure should indeed reside with the renderer and not the font. I've pushed out the changes in the above commit, please let me know your opinion!
