### ISSUE TITLE
Methods such as (*Context).Fill ignore coordSystem and call RenderPath directly

### ISSUE THREAD

**Issue by eihigh** [tdewolff/canvas#182]
If the coordSystem is CartesianIV, [ReflectY is required](https://github.com/tdewolff/canvas/blob/master/canvas.go#L449), but `*Context`'s Fill, Stroke, and FillStroke do not do that and calls RenderPath directly.

One solution is to call DrawPath instead of calling RenderPath directly. As follows:

```diff
diff --git a/canvas.go b/canvas.go
index 984e017..48f306a 100644
--- a/canvas.go
+++ b/canvas.go
@@ -419,9 +419,10 @@ func (c *Context) Close() {
 // Fill fills the current path and resets the path.
 func (c *Context) Fill() {
        style := c.Style
-       style.StrokeColor = Transparent
-       c.RenderPath(c.path, style, c.view)
+       c.Style.StrokeColor = Transparent
+       c.DrawPath(0, 0, c.path)
        c.path = &Path{}
+       c.Style = style
 }
```

RenderAsPath also calls RenderPath directly, but since it is being passed m transformed by DrawText, there seems to be no problem so far.

**Comment by tdewolff** [comment]
Thanks for the issue, should be fixed now!
