### ISSUE TITLE
How to fill a canvas with a loaded image?

### ISSUE THREAD

**Issue by jjude** [tdewolff/canvas#185]
I am using `ctx.DrawImage(0, 0, bimg, canvas.DefaultResolution)` to draw the image. But I want to fill the image to the canvas size. Is it possible to achieve it? How?

_I'm sorry I am asking a help in issues. But I didn't find any other mode where I can ask for help._

**Comment by tdewolff** [comment]
Hi Joseph, that depends on the size of the image and the size of the canvas. I've added a method `canvas.FitImage` to the library that should help in your case! See the commit above.
