### ISSUE TITLE
Writing to a file doesn't wait for the file to be written to before returning

### ISSUE THREAD

**Issue by Toffee1347** [tdewolff/canvas#186]
If you have any canvas, then try writing the data to a PNG (I'm guessing this will also happen with other data types) with this code:

```GO
renderers.Write("<PATH>", c)
```

The function will return before the file has been written to. This is a problem for me since I am connecting this with a webserver, so am receiving both `ERR_EMPTY_RESPONSE` and `ERR_CONTENT_LENGTH_MISMATCH` errors some of the time. The way I can fix this currently is to add a very small delay between the function returning and the webserver responding with an image, but this isn't ideal.

Would it be possible to either make the function return once the file is written, or add some kind of option to allow it?

**Comment by Toffee1347** [comment]
Looks like this was actually an issue with the webserver package, thanks for the cool lib!

**Comment by tdewolff** [comment]
Thanks for the follow-up, indeed `canvas` closes the file before returning, so it must be a problem at the webserver side.
