### ISSUE TITLE
SVG text is upside down / flipped on y axis

### ISSUE THREAD

**Issue by davidhtims** [tdewolff/canvas#192]
I'm sorry, I must be missing a setting somewhere but I've looked at the docs and issues ...
The output SVG is upside down?

```
        fontFamily := canvas.NewFontFamily("Geneva")
	if err := fontFamily.LoadFontFile("/System/Library/Fonts/Geneva.ttf", canvas.FontBold); err != nil {
		panic(err)
	}

	face := fontFamily.Face(80.0, canvas.Black, canvas.FontBold, canvas.FontNormal)
	path, _, err := face.ToPath(text)
	if err != nil {
		panic(err)
	}

	tpl := `<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" height="400" width="800">
		<path d="%s" />
	</svg>`
	fmt.Printf(tpl, path.ToSVG())
```

**Comment by tdewolff** [comment]
Canvas works in the first Cartesian quadrant (the default for mathematics)
while SVG uses the fourth. You need to flip the canvas vertically, setting
the context View for example.

**Comment by shuqingzai** [comment]
I also encountered the same problem, and tried both ctx.ReflectX() and ctx.ReflectY(), it seems to have no effect

**Comment by tdewolff** [comment]
Taking a second look, as in your case you print the path directly within an SVG, you need to transform the path manually. The last line should read, given that your SVG height is `400`:

```go
fmt.Printf(tpl, path.Transform(canvas.Identity.ReflectYAbout(400.0 / 2.0)).ToSVG())
```

Please re-open the issue and let me know if your still have trouble!
