### ISSUE TITLE
panic: glGetActiveSubroutineName

### ISSUE THREAD

**Issue by Aivaki** [tdewolff/canvas#194]
```
//go:build cgo

package main

import (
	"fmt"
	"runtime"

	"github.com/go-gl/gl/v4.1-core/gl"
	"github.com/go-gl/glfw/v3.3/glfw"
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/opengl"
)

func main() {
	runtime.LockOSThread()

	ogl := opengl.New(200.0, 100.0, canvas.DPMM(5.0))
	//ctx := canvas.NewContext(ogl)
	//if err := canvas.DrawPreview(ctx); err != nil {
	//	panic(err)
	//}

	// Set up window
	if err := glfw.Init(); err != nil {
		panic(err)
	}
	defer glfw.Terminate()

	glfw.WindowHint(glfw.Resizable, glfw.False)
	glfw.WindowHint(glfw.ContextVersionMajor, 3)
	glfw.WindowHint(glfw.ContextVersionMinor, 2)
	glfw.WindowHint(glfw.OpenGLProfile, glfw.OpenGLCoreProfile)
	glfw.WindowHint(glfw.OpenGLForwardCompatible, glfw.True)

	width, height := 800, 400
	window, err := glfw.CreateWindow(width, height, "", nil, nil)
	if err != nil {
		panic(err)
	}
	window.MakeContextCurrent()

	if err := gl.Init(); err != nil { // panic: glGetActiveSubroutineName
		panic(err)
	}
	version := gl.GoStr(gl.GetString(gl.VERSION))
	fmt.Println("OpenGL version", version)

	// Compile canvas for OpenGl
	ogl.Compile()

	gl.Enable(gl.BLEND)
	gl.BlendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)

	gl.ClearColor(1, 1, 1, 1)
	for !window.ShouldClose() {
		gl.Clear(gl.COLOR_BUFFER_BIT)

		// Draw compiled canvas to OpenGL
		ogl.Draw()

		glfw.PollEvents()
		window.SwapBuffers()
	}
}
```
>https://github.com/tdewolff/canvas/blob/master/examples/opengl/main.go

**Comment by tdewolff** [comment]
This seems to be a problem with your system and OpenGL, and not with `canvas`. I don't think I can help you with this, try with the go-gl library...

**Comment by Aivaki** [comment]
> This seems to be a problem with your system and OpenGL, and not with `canvas`. I don't think I can help you with this, try with the go-gl library...

It is this example that causes panic. Other packages and OpenGL itself work fine

**Comment by Aivaki** [comment]
> > This seems to be a problem with your system and OpenGL, and not with `canvas`. I don't think I can help you with this, try with the go-gl library...
> 
> It is this example that causes panic. Other packages and OpenGL itself work fine. I can provide more information if needed

I also noticed that when changing "github.com/go-gl/gl/v4.1-core/gl" -> "github.com/go-gl/gl/all-core/gl" panic is not caused, but other errors appear (right now I can't say which ones)

**Comment by tdewolff** [comment]
Your problem happens at `gl.Init()`, that has nothing to do with `canvas`. Removing all canvas related code will also produce the panic...

**Comment by Aivaki** [comment]
> Your problem happens at `gl.Init()`, that has nothing to do with `canvas`. Removing all canvas related code will also produce the panic...

Are you sure? Next example works well on my PC... https://github.com/go-gl/example/tree/master/gl41core-cube

I'll come home and try to figure out what's wrong

**Comment by tdewolff** [comment]
This must be a problem with your OpenGL version somehow. The code is using v4.1-core just like the example you mentioned, so it is weird that one works and the other not. You can try and remove all `canvas` related code and should observe the same panic (please confirm).

The only thing that comes to mind perhaps is to try and change
```
	glfw.WindowHint(glfw.ContextVersionMajor, 3)
	glfw.WindowHint(glfw.ContextVersionMinor, 2)
```
to 
```
	glfw.WindowHint(glfw.ContextVersionMajor, 4)
	glfw.WindowHint(glfw.ContextVersionMinor, 1)
```

**Comment by tdewolff** [comment]
This must be a problem with your OpenGL version somehow. The code is using v4.1-core just like the example you mentioned, so it is weird that one works and the other not. You can try and remove all `canvas` related code and should observe the same panic (please confirm).

The only thing that comes to mind perhaps is to try and change
```
	glfw.WindowHint(glfw.ContextVersionMajor, 3)
	glfw.WindowHint(glfw.ContextVersionMinor, 2)
```
to 
```
	glfw.WindowHint(glfw.ContextVersionMajor, 4)
	glfw.WindowHint(glfw.ContextVersionMinor, 1)
```

**Comment by Aivaki** [comment]
> This must be a problem with your OpenGL version somehow. The code is using v4.1-core just like the example you mentioned, so it is weird that one works and the other not. You can try and remove all `canvas` related code and should observe the same panic (please confirm).
> 
> The only thing that comes to mind perhaps is to try and change
> ```
> 	glfw.WindowHint(glfw.ContextVersionMajor, 3)
> 	glfw.WindowHint(glfw.ContextVersionMinor, 2)
> ```
> to 
> ```
> 	glfw.WindowHint(glfw.ContextVersionMajor, 4)
> 	glfw.WindowHint(glfw.ContextVersionMinor, 1)
> ```

Thank you for your time! I'll check it all out soon

**Comment by jostasi** [comment]
I get the same error. Did you figure out what caused the error? The GL library probably failed to load this specific function. But I don't know GL well enough.

**Comment by Aivaki** [comment]
> ```
> 	glfw.WindowHint(glfw.ContextVersionMajor, 3)
> 	glfw.WindowHint(glfw.ContextVersionMinor, 2)
> ```
> 
> to
> 
> ```
> 	glfw.WindowHint(glfw.ContextVersionMajor, 4)
> 	glfw.WindowHint(glfw.ContextVersionMinor, 1)
> ```
You won't believe it, but it actually helped (I thought the problem was something else). Now it works!

I suggest making changes to the [example](https://github.com/tdewolff/canvas/blob/master/examples/opengl/main.go) to finally close this problem

**Comment by tdewolff** [comment]
Thanks for the feedback, example is fixed!
