### ISSUE TITLE
[Question] How to read svg as layer

### ISSUE THREAD

**Issue by shuqingzai** [tdewolff/canvas#197]
I saw that there are `NewPNGImage` and `NewJPEGImage` that can directly use files as layers, but I don’t seem to see the `svg` type

May I ask how to import the svg file as a layer instead of passing in the svg content string directly?

**Comment by tdewolff** [comment]
There is no function to read in an SVG file entirely (yet). What you can do is read a `<path d="..."/>` element by passing the contents of the `d` attribute to `path := canvas.ParseSVG(d)` and draw that path. Reading in an SVG file is quite ambitious but may be implemented in the future!
