### ISSUE TITLE
Is it currently possible to generate multi-page pdf?

### ISSUE THREAD

**Issue by oliverpool** [tdewolff/canvas#20]
Your library looks great, and I am thinking about using it to generate multipage PDFs.

As far as I see this is currently not possible using the public API.

The `pdfWriter` (not exported) struct seems to be ready for it (with its `NewPage` method).

I can't reuse the same `io.Writer` for `NewPDF` (only exported way to trigger the `NewPage` method), because it calls `newPDFWriter` which always writes `w.write("%%PDF-1.7\n")` at the beginning.

---

I have no idea how multipages work in pdfs, but I think that this feature could be implemented the following way:
- add an exported `NewPage(width, height float64)` method to `PDF`, which would forward the call to `w.pdf.NewPage` and replace `w` with the newly created page

What do you think?
I could try to craft a MR if you think that this sounds like a good idea.

**Comment by tdewolff** [comment]
That sounds like an excellent idea! If you want to send a PR I'd be happy to review and merge ;-)
