### ISSUE TITLE
panic in boolean path operation

### ISSUE THREAD

**Issue by omniskop** [tdewolff/canvas#200]
I've stumbled upon an index out of range error while using boolean path operations.
After a bit of trial and error I could create this minimal example:

```go
package main

import (
	"github.com/tdewolff/canvas"
)

func main() {
	radius := 0.7

	path := canvas.Circle(radius)
	path = path.Or(canvas.Rectangle(1, 1).Translate(0, -radius))
	_ = path
}
```

This results in the following panic: (some paths are shortened)
```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/tdewolff/canvas.collisions({0xc0001a9bb8, 0x1, 0x1255d08?}, {0xc0001a9bc0, 0x1, 0xc0002c7c18?}, 0x0)
        .../go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/path_intersection.go:885 +0x1865
github.com/tdewolff/canvas.boolean(0x0?, 0x1, 0xc00000e540?)
        .../go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/path_intersection.go:171 +0x266
github.com/tdewolff/canvas.(*Path).Or(...)
        .../go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20221230020303-9eb6d3934367/path_intersection.go:81
main.main()
        main.go:11 +0x5c
```

While writing this issue I noticed that depending on what values you use It's also possible to get a panic with the message: "panic: bug: number of intersections must be even".

I'm still not entirely sure of the importance of the specific values but there are some patterns.
It seems the rectangle width has to always be larger than the radius by some amount. If the height of the rectangle is smaller than the radius the error will be about the number of intersections not being equal and when it is larger the index-out-of-range will occur.
What seems to be important is that the rectangle has to be translated by the radius, positive or negative doesn't seem to matter though. The actual boolean operation doesn't matter either as the issue also occurs with other ones.

I hope this helps and thanks for creating this great library!

**Comment by tdewolff** [comment]
Thanks for the elaborate issue, it is very likely that there is one bug
that causes both messages but I'll test that anyways. I hope to fix this
next week!

**Comment by tdewolff** [comment]
This has now been fixed!

**Comment by omniskop** [comment]
Thank you!
