### ISSUE TITLE
[question] How to force a overflow text to wrap

### ISSUE THREAD

**Issue by p1usign** [tdewolff/canvas#206]
here is the demo:

```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	fontLatin := canvas.NewFontFamily("latin")
	if err := fontLatin.LoadLocalFont("DejaVuSerif.ttf", canvas.FontRegular); err != nil {
		panic(err)
	}
	fontface := fontLatin.Face(24.0, canvas.Black, canvas.FontRegular, canvas.FontNormal)

	W := 80.0
	H := 80.0

	c := canvas.New(W, H)
	ctx := canvas.NewContext(c)
	ctx.SetCoordSystem(canvas.CartesianIV)
	ctx.SetFillColor(canvas.White)
	ctx.DrawPath(0, 0, canvas.Rectangle(W, H))

	txt := canvas.NewTextBox(fontface, "abcdefghijklmnopqrstuvwxyz", 10.0, 0.0, canvas.Left, canvas.Top, 0, 0)

	ctx.DrawText(0, 0, txt)

	renderers.Write("test.png", c, canvas.DPMM(10.0))
}
```

![test](https://user-images.githubusercontent.com/35355389/225288169-f96a4b15-070f-4f41-a784-22423f542b5b.png)

What should I do if I want to force a long word to wrap?

**Comment by tdewolff** [comment]
You should insert `\u00AD` unicode characters at places where a breakpoint is feasible:

```go
// When to use what?
//   Start a new line: \n
//   Space that doesn't break: \u00A0
//   Word break opportunity with hyphenation: \u00AD
//   Word break opportunity without hyphenation: \u200B
//   Prevent word break: \u2060
```

**Comment by p1usign** [comment]
> You should insert `\u00AD` or `\u2008` unicode characters at places where a breakpoint is feasible:
> 
> ```go
> // When to use what?
> //   Start a new line: \n
> //   Space that doesn't break: \u00A0
> //   Word break opportunity with hyphenation: \u00AD
> //   Word break opportunity without hyphenation: \u200B
> //   Prevent word break: \u2060
> ```

Is there a way to autocomplete this functionality in ``newtextbox``?

**Comment by tdewolff** [comment]
What do you mean? There is no automatic way to do this since every language or input is different. Assuming that `abcdefghijklmnopqrstuvwxyz` is a word, where should it be split? I don't think that splitting at any character is a good idea, unless it is Chinese/Japanese/Korean etc. There is WIP to add automatic hyphenation support though, but to support many languages would be quite some work...
