### ISSUE TITLE
Race condition when calling ToRasterizer on a path

### ISSUE THREAD

**Issue by farhaven** [tdewolff/canvas#208]
Commit 5114238b14c768e1326188138fffac72f0d5531a made `canvas.(*Path)`'s `ToRasterizer` function unsafe to call concurrently, because it modifies the global `Tolerance` value.

Race conditions look roughly like this (the odd paths come from building with Bazel, but they're readable nonetheless):

```
WARNING: DATA RACE
Read at 0x000105a54628 by goroutine 428:
  github.com/tdewolff/canvas.(*Path).ToRasterizer()
      external/com_github_tdewolff_canvas/path.go:1930 +0x54
  github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath()
      external/com_github_tdewolff_canvas/renderers/rasterizer/rasterizer.go:120 +0xa60
  github.com/tdewolff/canvas.(*Canvas).RenderTo()
      external/com_github_tdewolff_canvas/canvas.go:707 +0x554
  [ ... confidential part of stack trace elided ... ]

Previous write at 0x000105a54628 by goroutine 435:
  github.com/tdewolff/canvas.(*Path).ToRasterizer()
      external/com_github_tdewolff_canvas/path.go:1933 +0xd4
  github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath()
      external/com_github_tdewolff_canvas/renderers/rasterizer/rasterizer.go:113 +0x74c
  github.com/tdewolff/canvas.(*Text).RenderAsPath()
      external/com_github_tdewolff_canvas/text.go:1145 +0x55c
  github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderText()
      external/com_github_tdewolff_canvas/renderers/rasterizer/rasterizer.go:128 +0xb8
  github.com/tdewolff/canvas.(*Canvas).RenderTo()
      external/com_github_tdewolff_canvas/canvas.go:709 +0x5bc
  [ ... confidental part of stack trace elided ... ]
```

the last call in the confidential part of the stack trace is roughly shaped like this:

```go
c := canvas.NewFromSize(canvas.A4)
ctx := canvas.NewContext(c)

drawToCanvas(ctx)

resolution := canvas.DPI(300)

img := image.NewRGBA(image.Rect(0, 0, int(c.W*resolution.DPMM()+0.5), int(c.H*resolution.DPMM()+0.5)))
draw.Draw(img, img.Bounds(), image.NewUniform(color.White), image.Point{}, draw.Over)

raster := rasterizer.FromImage(img, canvas.DPI(300), canvas.DefaultColorSpace)
c.RenderTo(raster) // <- race detected here
raster.Close()
```

I think a reasonable solution to this would be to either protect the changed tolerance value with a mutex (which would essentially single-thread all operations that go through this path, which sounds bad from a performance-vs-gain perspective) or to make the tolerance a local value of `ToRasterizer` and pass it through to called functions as a parameter or something like that.

**Comment by tdewolff** [comment]
Thanks for the bug report. The way the tolerance is adjusted is indeed a bit sloppy. The solution however requires a bit refactor in the way that functions are defined. The global `Tolerance` is used in many places and would need to be passed along everywhere. I will keep you updated.

**Comment by tdewolff** [comment]
I've fixed the issue and added the `tolerance` parameter for explicit control when calling the `Flatten()`, `Stroke()`, and `Offset()` functions.

**Comment by farhaven** [comment]
Sorry for getting back so late, I just wanted to drop a note that I appreciate the quick fix. Thanks :)
