### ISSUE TITLE
Text hyphenation is not working when text box width is not set.

### ISSUE THREAD

**Issue by orzel7** [tdewolff/canvas#209]
When newline symbol is used and textbox width equals to 0, text is rendered as a single line.
txt := canvas.NewTextBox(face, "Arc Sensor \nChannel 1", 0, 0, canvas.Middle, canvas.Top, 0, 0.5)

**Comment by tdewolff** [comment]
Thanks, should be fixed now!

**Comment by orzel7** [comment]
Great job, thank you a lot!
