### ISSUE TITLE
RichText.ToText panics

### ISSUE THREAD

**Issue by orzel7** [tdewolff/canvas#210]
It looks, RichText.ToText panics when passing empty string
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/tdewolff/canvas.(*RichText).ToText(0xc001d4f758, 0x0, 0x0, 0x1, 0x5, 0x0?, 0x0)
	............./vendor/github.com/tdewolff/canvas/text.go:674 +0x3990

**Comment by tdewolff** [comment]
Not sure why, but I wasn't able to reproduce, though reading the code it should've panicked! Can you check if it is fixed now?

**Comment by orzel7** [comment]
Thank you, this commit fixes the problem.
