### ISSUE TITLE
How to clear the canvas as we do in js?

### ISSUE THREAD

**Issue by lightgmco** [tdewolff/canvas#211]
The only way is to draw a canvas size rectangle with background color?But default background color is transparent, and I tried using transparent bgColor,but has no effect.
Annother question is about fyne.After I added the c.content() into container,I used ctx to change the canvas(add more lines),then I tried to refresh it using "c.content().refresh()",but it didn't work.

**Comment by lightgmco** [comment]
> Regarding your first question, if you use the `Canvas` renderer, you can call `c.Reset()` to clear the canvas. If you directly use another renderer (such as the rasterizer) this is usually not possible and you'd need to draw a rectangle the size of the canvas of white (default color is black, you need to set the fill color to white). In the case of the Fyne renderer you can however, since it is a wrapper around `Canvas`. You can thus do something like:
> 
> ```go
> package main
> 
> import (
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"github.com/tdewolff/canvas"
> 	canvasFyne "github.com/tdewolff/canvas/renderers/fyne"
> )
> 
> func main() {
> 	c := canvasFyne.New(200.0, 100.0, canvas.DPMM(10.0))
> 	ctx := canvas.NewContext(c)
> 	if err := canvas.DrawPreview(ctx); err != nil {
> 		panic(err)
> 	}
> 
>         c.Reset() //  THIS WILL CLEAR THE CANVAS
> 
> 	a := app.New()
> 	w := a.NewWindow("Canvas")
> 	w.Resize(fyne.Size{800, 400})
> 	w.SetContent(c.Content())
> 	w.ShowAndRun()
> }
> ```

Thanks for your answer.
I tried c.reset(),it worked very well.
But in fyne, I tried to update the c.content(),failed again.
Because I need more elements in the main fyne window,so I used Window.Canvas().Overlays().Add(c.content())
After that ,after some events,I need to redraw the canvas,but I can't refresh the content.

**Comment by tdewolff** [comment]
I don't understand what your problem is. Honestly I'm not a Fyne expert, but if there is a bug with Canvas I'd be happy to help.

**Comment by lightgmco** [comment]
I found a way to solve it.
I used a fyne.canvas.RasterFromImage,and the RasterFromImage has a generator which can be modified.
myRaster.Generator = func(w, h int) image.Image {
		return c.Content().(*canvas.Image).Image
	}
after I changed the canvas content =>myRaster.Refresh()=>Done!
My project need to render ATC map with route/waypoints, when nesseary, map need to be transformed and refreshed by user.In the past I did this using js and html5.Recently,I switch my project to golang for 'goroutine',but golang dosen't offer many choices for me to draw the UI which need high 2d redering performance.Thanks very much for you canvas project,it's very helpful!
By the way ,any other suggestion to generate the canvas.content(* canvas.image).Image faster?Using another renderer?

**Comment by tdewolff** [comment]
Great! Unfortunately you're stuck with a rasterizer (slow) and probably sampling in Fyne. Not sure if there's a way to directly draw to the screen with Fyne, but the rasterizer is hard to optimize, it is already using a high-performance implementation. You could draw to a smaller canvas size and stretch the result, or use (way) less path commands, or increase the `PixelTolerance` value.

**Comment by lightgmco** [comment]
I Set the canvas size = display area size, 1:1 for pixel, I don't know if it will help.
And I split the map into several layers and use go routine to update the content .
I will try use image rederer in fyne since you said it has better performance.
