### ISSUE TITLE
[question] Image vs Path origin inconsistency

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#212]
Hi again,

While I've been integrating the new coordinate system changes to our codebase to drop our Y-axis recalculation code, I've noticed that some render components handle the rendering origin differently and thus cause some inconsistencies within our code.

We use CartesianIV coordinate system now.

One such case is when we render rectangles, we call `dc.DrawPath(n.X, n.height+n.Y, canvasPath)` and have to offset the Y axis by the rectangle's height to ensure the anchor is set at the bottom-left of the node.

Meanwhile, images handle such situations and recalculate the origin based on the coordinate system used. As seen here:
```go
func (c *Context) DrawImage(x, y float64, img image.Image, resolution Resolution) {
	if img.Bounds().Size().Eq(image.Point{}) {
		return
	}

	coord := c.coord(x, y)
	m := Identity.Translate(coord.X, coord.Y).Mul(c.view).Scale(1.0/resolution.DPMM(), 1.0/resolution.DPMM())
	if c.coordSystem == CartesianIII || c.coordSystem == CartesianIV {
		m = m.Translate(0.0, -float64(img.Bounds().Size().Y))
	}
	if c.coordSystem == CartesianII || c.coordSystem == CartesianIII {
		m = m.Translate(-float64(img.Bounds().Size().X), 0.0)
	}
	c.RenderImage(img, m)
}
```

Is there a specific reason for why only some render components recalculate the position? Could it be improved on the canvas side potentially?

Thank you.

**Comment by tdewolff** [comment]
Good point, it's however not very straightforward to fix this, and I'd be happy for some input!

Text boxes are always anchored top-left, and text lines are always anchored on the baseline. Images are anchored to the corner closest to the origin, that is bottom-left for CartesianI and top-left for CartesianIV. For paths there is a fixed starting point (the first MoveTo) and we don't change anything based on the coordinate system.

What I can do to fix this, is to flip the vertical axis of the path for CartesianIV (i.e. ReflectY) which actually works quite well if we compare it to SVG paths. SVG paths are in CartesianIV, and when copying the path command-for-command you'd need to flip the Y axis in `canvas` for it to display correctly. Now if we were to flip the Y axis for paths in the CartesianIV coordinate system, this would fix this incosistency and make it a bit more intuitive for CartesianIV users (perhaps the majority).

**Comment by tdewolff** [comment]
I've pushed the proposal above, this actually works well when together with `ParseSVG`.

**Comment by zpl-zak** [comment]
Thank you, I will test it out and let you know how things work!

**Comment by zpl-zak** [comment]
Hi again, rendering works fine on our end, it is much easier for us to render certain elements, thank you again for your help! If there's any info I can provide related to this issue let me know.
