### ISSUE TITLE
Render doesn't work as expected

### ISSUE THREAD

**Issue by lightgmco** [tdewolff/canvas#213]
question1:
I have a canvas and its ctx, I want to draw some elements and stroke(),then change ctx.strokeColor, continue to draw more elements ,it doesn't work any more.
question2:
I tried the ctx.RenderPath() and canvas.RenderPath(),both failed,no output,I even used canvas.Identity as matrix,configed the style :
gocanvas.Style{
	Stroke:      gocanvas.Paint{Color: color.RGBA{92, 92, 92, 255}},
	StrokeWidth: 2,
	DashOffset:  0,
	Dashes:      []float64{0},
}.

**Comment by lightgmco** [comment]
question3: I created 3 canvas one by one,set ctx one by one, but can only draw on the first canvas,that's weired.

**Comment by tdewolff** [comment]
Can you please write more clearly? I really don't understand any of your problems. Post the code you're using, the result you're expecting and the result you're getting instead.

**Comment by lightgmco** [comment]
import (
	"image/color"
	gocanvas "github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/rasterizer"
)
func main() {
	var DashRingStyle = gocanvas.Style{
		Stroke:      gocanvas.Paint{Color: color.RGBA{81, 102, 102, 1}},
		StrokeWidth: 1,
		Dashes:      []float64{5, 5},
	}
	rc := rasterizer.New(1920, 1080, gocanvas.DPMM(2), gocanvas.DefaultColorSpace)
	p := &gocanvas.Path{}
	m := gocanvas.Identity
	p.MoveTo(0, 0)
	p.LineTo(1500, 1500)

	rc.RenderPath(p, DashRingStyle, m)

}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1165602]

goroutine 1 [running]:
github.com/tdewolff/canvas.offsetSegment(0xc0022b43f0, 0x3fe0000000000000, {0x0, 0x0}, {0x0, 0x0}, 0x0?)
        /Users/GaoMing/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230330213711-30ef6b683296/path_stroke.go:468 +0x2042
github.com/tdewolff/canvas.(*Path).Stroke(0x0?, 0x3ff0000000000000, {0x0, 0x0}, {0x0, 0x0}, 0x0?)
        /Users/GaoMing/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230330213711-30ef6b683296/path_stroke.go:574 +0x118
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0xc0022b2000, 0xc0022b4000?, {{{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0}}, {{0x51, 0x66, ...}, ...}, ...}, ...)
        /Users/GaoMing/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20230330213711-30ef6b683296/renderers/rasterizer/rasterizer.go:84 +0x23b
main.main()
        /Users/GaoMing/Downloads/0405/main.go:22 +0x278
exit status 2

**Comment by tdewolff** [comment]
You forgot to set the stroke capper and joiner, which are `nil` and throw a panic. I've fixes this by stating that when `nil`, the capper is assumed to be `ButtCap, and the joiner `MiterJoin`.

**Comment by lightgmco** [comment]
So I need to reinstall the canvas project then it could work?

**Comment by tdewolff** [comment]
Yes, you should update the library with `go get -u github.com/tdewolff/canvas`
