### ISSUE TITLE
[question] Detect text overflowing textbox

### ISSUE THREAD

**Issue by ernierasta** [tdewolff/canvas#217]
Hi!
First - thank you for such wonderful library, I just discovered it and it is amazing. Sorry for probably primitive question ... Can I detect that text is longer then defined TextBox (will not render, as it is out of boundaries)? I would like to achieve "font scaling" (I will lower font size if text will not fit, check if it now fits, repeat until it fits).

BTW: Maybe it would be good to enable discussions for this repo?

**Comment by tdewolff** [comment]
Thanks for the kind words! I've enabled discussions for this repo.

I've added a function `Text.String` that returns the string content of the text box. This will allow you to confirm whether all text fits in the text box. Please let me know if there are any bugs w.r.t. missing spaces (such as at the beginning/end of lines). Does that work for you?

**Comment by ernierasta** [comment]
Taco, you are quick! It works like a charm. You just need to fix:
text.go, line 1191
there is `sb.Text()` should be `sb.String()`. Thank you!

**Comment by ernierasta** [comment]
So, as you probably suspected - we are missing space for every new row (TextSpan) of text. Now, question is, will there always be space which divide spans? I think we can assume that, but you know better. :-)

**Comment by tdewolff** [comment]
Not necessarily, but the problem is a little more complicated. I will need some time to work on this!

**Comment by ernierasta** [comment]
You are of course right. My primitive solution is:
```go
// TextString returns the content of the text box.
// WARNING: it may not work correctly for strings with
// double spaces!
func TextString(t *canvas.Text) string {
	sb := &strings.Builder{}
	t.WalkSpans(func(_, _ float64, span canvas.TextSpan) {
		if strings.HasSuffix(span.Text, " ") {
			sb.WriteString(span.Text)
		} else {
			sb.WriteString(span.Text + " ")
		}
	})
	return sb.String()
}
```

But it may work only for my usecase, as I will not have two space chars in row. And there are probably more potential problems ("hand made" spans, ...).

**Comment by pborges** [comment]
I see there is a bigger issue at works but I would love it if you could push the change suggested [here](https://github.com/tdewolff/canvas/issues/217#issuecomment-1501186050) 🙇  I can't compile master as is 😢

**Comment by tdewolff** [comment]
Done!

**Comment by pborges** [comment]
> Done!

WOW that was fast! Thank you, I have been playing with this library for a few hours now, its been very very useful!!

**Comment by tdewolff** [comment]
I've pushed out a fix so that `Text.String()` returns the exact string that is displayed (including spaces, explicit new lines, etc.). Let me know if it works well!

**Comment by ernierasta** [comment]
Hi! I can confirm, that latest change works great! Thank you again!
