### ISSUE TITLE
RotateAbout post-rotate positioning issue

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#219]
Hi,

We've encountered an issue with the latest canvas version. As we use RotateAbout to rotate around the node's center, the node's position becomes incorrectly calculated. The behavior we'd expect is that RotateAbout with (width/2 and height/2) offset provided would rotate about the center point of our node. 

Instead, it feels as if the order of operations was wrong; since RotateAbout instead shifts the node in the offset vector's direction, performs rotation, and then translates it back, the result does appear correct (as seen in pic). Still, it does not achieve the intended goal; negating the offset vector did not help. However, it's likely closer to the behavior we're trying to emulate.

We use CartesianIV, although it doesn't have much to do with it. We perceive a different behavior with the build made before the coordinate system changes.

![mstsc_TkuaMP2tZ6](https://user-images.githubusercontent.com/9026786/231102997-d96170c0-3829-4313-885f-131e9d32cfb2.jpg)
(each rectangle describes RotateAbout args used)

I'll also attach the code itself:
[canvas_bug.zip](https://github.com/tdewolff/canvas/files/11198424/canvas_bug.zip)

**Comment by tdewolff** [comment]
I've pushed out a fix!

**Comment by zpl-zak** [comment]
Hi, unfortunately, with the demo above, after changing all angles to become positive, the text does not seem to follow the rotation of the rectangles. On top of that, even in the default coord system, rectangles appear incorrectly positioned.

CartesianIV with 90 deg rotation:
![mstsc_Ntdwf3aiX4](https://user-images.githubusercontent.com/9026786/231676678-ff3a0f10-67c9-4275-bffd-f23f9289cf99.jpg)

Default coord system with 90 deg rotation:
![mstsc_UL7arATHcx](https://user-images.githubusercontent.com/9026786/231676892-0d1a5ebf-ac83-4984-a8c1-ab604d84416c.jpg)

**Comment by tdewolff** [comment]
Yes, in the IV coordinate system, clockwise rotation is positive (the same is true in SVGs). The rectangles look fine to me (which one is wrong in your opinion?) but text rotation is off. I'll push out a fix asap.

**Comment by zpl-zak** [comment]
Hi, our goal is to rotate a rectangle/text about its center, however we are not able to pull that off on the current canvas version. Our assumption was to rotate about rect width/2 and height/2, but that makes the rect instead get pushed out of its initial position.

![Milton_jTGu7Ak5RL](https://user-images.githubusercontent.com/9026786/231971613-66ccb9c1-4776-4083-8c64-91f59f5b7d63.jpg)


1) initial rectangle position
2) rotation about rectangle's center we want to perform
3) how the rotation looks like in the current canvas build (`ctx.RotateAbout(90, width/2, height/2)`)

**Comment by zpl-zak** [comment]
It looks like the render is fine now, thanks again for the help!

**Comment by tdewolff** [comment]
The text objects are still not positioned as expected, I'm working on a fix.

**Comment by tdewolff** [comment]
Well, that should do it, let me know if you run into any trouble. Be aware that I'm working actively on improving the library, I'm happy to get your feedback!
