### ISSUE TITLE
Can't set linear/radial gradient as a fill pattern

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#220]
Hi,

it looks like one of the latest commits broke gradient support since when SetFillPattern is called, it errors out because the gradient class lacks the ClipTo method.

`cannot use g (variable of type *canvas.LinearGradient) as canvas.Pattern value in argument to dc.SetFillPattern: *canvas.LinearGradient does not implement canvas.Pattern (missing method ClipTo)`

**Comment by zpl-zak** [comment]
Closing this one with a note that the gradients are now set using `SetFillGradient` call.

**Comment by tdewolff** [comment]
Yes sorry for the breakage, I'm working actively on adding gradient/hatch/pattern support for all renderers! You can also use `ctx.SetFill` instead!
