### ISSUE TITLE
Hi, how to convert the image of SVG path to PNG/PDF? Without setting the size, because the size is not known.

### ISSUE THREAD

**Issue by PublicWorld** [tdewolff/canvas#222]

**Comment by tdewolff** [comment]
Can you be more precise? What is the `image of SVG path`? I guess you have an SVG path, and you convert it to a path in canvas using `p := canvas.MustParseSVG("M1,0L8,6...")`? You can then rasterize it to a PNG or convert it to a PDF. What do you mean you don't want to set the size? You can use the `Canvas` drawing target (default) and use e.g.:

```go
p := canvas.MustParseSVG("M1,0L8,6...")

c := canvas.New(0,0)
ctx := canvas.NewContext(c)
ctx.DrawPath(x, y, p)

// fit canvas to path boundaries with a border of 1mm
c.Fit(1.0)

renderers.Write("out.png", c, canvas.DPMM(10))
renderers.Write("out.svg", c)
```

**Comment by NumberCode** [comment]
Thanks for your suggestion.
I tried this method, but seems it can't parse this svg file, could you help to check this? and can we support this svg format?

![1681640166](https://user-images.githubusercontent.com/12987627/234027601-dff906ec-a900-42b3-90b9-00b85642b451.svg)

**Comment by tdewolff** [comment]
This library does not parse entire SVG files or any other files yet, it is on the roadmap. You can only parse an SVG path to a canvas path. I've renamed the parse function to avoid confusion.

**Comment by tdewolff** [comment]
There is now basic functionality to parse and draw a full SVG. This will be tracked from https://github.com/tdewolff/canvas/issues/235

**Comment by typomedia** [comment]
Hi! Is it now possible to raster a svg to a pixel based image format like png?

**Comment by tdewolff** [comment]
Yes you can:

```go
package main

import (
    "os"

    "github.com/tdewolff/canvas"
    "github.com/tdewolff/canvas/renderers"
)

func main() {
    f, err := os.Open("example.svg")
    if err != nil {
        panic(err)
    }

    c, err := canvas.ParseSVG(f)
    if err != nil {
        panic(err)
    }

    renderers.Write("example.png", c, canvas.DPMM(96.0/25.4))
}
```

**Comment by shachardevops** [comment]
@tdewolff there is an option to parse the SVG to png ? and not to a png file - the type is image.Image

**Comment by tdewolff** [comment]
I don't fully understand your question, but if you want to parse an SVG and output an `image.Image`, you can use the `rasterizer.Draw` function in `github.com/tdewolff/canvas/renderers/rasterizer`:

```go
img := rasterizer.Draw(c, canvas.DPMM(96.0/25.4), canvas.DefaultColorSpace)
```
