### ISSUE TITLE
SVG problem with fill and stroke

### ISSUE THREAD

**Issue by ernierasta** [tdewolff/canvas#224]
Hi,
I suspect that svg renderer is WIP, but as it is most interesting for me, it would be amazing if it will improve a bit. ;-)

Currently there is problem with stroke and fill - it is not written into svg output. Here as simple code as I can get:

```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	c := canvas.New(100, 60)
	ctx := canvas.NewContext(c)

	r := canvas.Rectangle(70.0, 50.0)
	ctx.SetFillColor(canvas.Salmon)
	ctx.SetStrokeColor(canvas.Aquamarine)
	ctx.SetStrokeWidth(2.0)
	ctx.DrawPath(5, 5, r)

	renderers.Write("output.png", c, canvas.DPI(96.0))
	renderers.Write("output.svg", c)
}
```
PNG:
![output](https://user-images.githubusercontent.com/956018/233179074-5d2159bb-721c-44ae-8c8f-caf747208be2.png)
Png renderer behaves as expected, but svg renderer creates black rectangle. 
SVG:
![output](https://user-images.githubusercontent.com/956018/233179147-58062eb8-9ae3-4a8c-b128-b518b481f440.svg)
Problem is with style, here is valid part of generated svg file:

```svg
<path d="M5 95H75V45H5z#fa8072#7fffd4" style="fill:;stroke:;stroke-width:2;stroke-miterlimit:2"/>
```
As result we get black rectangle. But if we fix it just adding colors where missing:

```svg
<path d="M5 95H75V45H5z#fa8072#7fffd4" style="fill:salmon;stroke:aquamarine;stroke-width:2;stroke-miterlimit:2"/>
```
We can see beautiful rectangle! ;-)

**Comment by ernierasta** [comment]
I had looked at it, problem is, that "style=" is written into string.Buffer, but actual color into io.Writer (). :-) Here is example of it:
https://github.com/tdewolff/canvas/blob/4e8637721eefda5770186e38704e6479972b1cee/renderers/svg/svg.go#L209
and the same with stroke:
https://github.com/tdewolff/canvas/blob/4e8637721eefda5770186e38704e6479972b1cee/renderers/svg/svg.go#L219
and maybe other.

Solution? Passing string.Buffer into `writePaint` (if not nil then use io.Writer)  or abandon string.Buffer and write directly to io.Writer?

**Comment by tdewolff** [comment]
Thanks for the issue! I've fixed the bug, please let me know how it goes. FYI the rasterizer, SVG, and PDF renderers are the principal targets of this library and should be working well. If you encounter any bugs I'd be happy to fix them!

**Comment by ernierasta** [comment]
Just confirming, that it is ok now. Thank you!
