### ISSUE TITLE
TextBox overflow detection on long word

### ISSUE THREAD

**Issue by ernierasta** [tdewolff/canvas#225]
Hi Taco!
TextBox-es again :slightly_smiling_face: . In current version, we can detect text overflowing TextBox by comparing original string with Text.String(), which works great if there is word missing (part of text separated by space). But if there is very long word in TextBox and it overflows - I do not know how to detect it.
There is a question, if text, that doesn't fit into given box should overflow, but this is not an issue from my perspective, I just need to know if it happens.

Here is example code:
https://gist.github.com/ernierasta/dd5a497fbb8a71484ef61381dbb115c7#file-main-go

I am creating box with text inside, textbox has **the same size** as rectangle, output is:
![output](https://user-images.githubusercontent.com/956018/234233121-d644f886-3824-48d6-8f97-f4de423f12fa.svg)

Can I somehow find out that this happened?

Have a great day!

**Comment by tdewolff** [comment]
I've added a `Text.Overflows` boolean that is true when text overflows.

NB: in your case it seems much more convenient to use the `canvas.NewTextLine(face, text, horizontal_align)` function which draws text, including newlines, except for alignment inside box or justification or multi lingual support. Note that you can get the exact width of a piece of text using the `FontFace.TextWidth(text)` function and size your box accordingly.

**Comment by ernierasta** [comment]
Thank you Taco, amazing work. 

Will test in few days and report back. 

Also thank you for an advise. I am doing opposite, basically creating tables and sizing text to fit the table, but will definitely check it out! 

All the best!
