### ISSUE TITLE
[question] Any way to detect if a certain character is present in a font family

### ISSUE THREAD

**Issue by p1usign** [tdewolff/canvas#229]
As the title, hope you can give some advice 🙏🏻

**Comment by tdewolff** [comment]
There is no way of selecting a font from a font family as it automatically selects it based on the font style when creating a font face. What you can do however, is loading in fonts directly without using a font family by using `canvas.LoadLocalFont` or `canvas.LoadFontFile`. The resulting `Font` structure has a method `GlyphIndex(rune) uint16` which returns a non-zero value when the rune is defined in the font. When you found the font that contains your character, use `font.Face(fontsize, color)` to get the font face needed for drawing text. Let me know how it goes!

**Comment by p1usign** [comment]
I have tried the method you gave and it solved my problem, thank u very much！
