### ISSUE TITLE
Consider splitting the Renderer into different packages

### ISSUE THREAD

**Issue by oliverpool** [tdewolff/canvas#24]
Currently this module is flat: all files and functions are in one package (except for the `font` and `htmlcanvas` package).

If someone wants to use this package to render PDF, it will still pull all the files and their dependencies (gonum for instance).

It should be possible to restructure this package to let the `Canvas` and `Context` at the root package (as well as the `Renderer` interface) and move all `Renderer` implementations to sub-packages (just like `htmlcanvas`).

Possible sub-packages (such structure could also encourage people to write their own Renderer in an external package):
- pdf
- raster (JPG, GIF, PNG)
- svg
- tex
- eps
- gonum

To prevent circular dependency, the `SaveXXX` methods will have to be moved to the respective sub-package (`pdf.WriteFile(canvas.Context, "filename.pdf")` for instance.

This could be implemented in 2 phases:
- duplicate the code into a sub-folder, to see how it feels and if it works, without breaking anything
- remove the code from the root package (breaking change - but since this package has no release yet, it is not bound by compatibility promises)

---

*Pros/Cons*

Benefits:
- clearer code organization (one responsibility per package)
- fewer dependencies, when a user exports to specific formats

Disadvantages:
- breaking change
- generation of the final file is a bit more complex from the user-side (`pdf.WriteFile(c, "filename.pdf")` instead of `c.SavePDF("filename.pdf")`)
- git history gets harder to follow

--- 

Are there any other issues, that I didn't mention?
Do you think it could be worth a try?

**Comment by tdewolff** [comment]
In general I was thinking the same, i.e. putting each renderer in a separate directory. For HTML Canvas this is necessary due to its different compilation target. For the others it's a bit more complicated like you indicated due to the `c.SaveXXX` methods (which I thought were really nice), unless `Canvas` would be put in a separate directory as well (though not sure I like a package `github.com/tdewolff/canvas/canvas` to have a struct called `Canvas`).

Otherwise, I find that in Go some projects prefer to keep everything in one directory to avoid these problems. I don't really have a problem so far with the number of Go files in the root directory, but if more renderers are added this may be necessary.

We could also put all renderers in a directory called `renderers`? Anyways, in general I agree with you but I'm not sure if it's worth the trouble. 

What about keeping the renderers in the root directory and moving the `Path` code into `path` (also, polyline, shapes, util, etc)? And all font related stuff into `font`...

**Comment by oliverpool** [comment]
> What about keeping the renderers in the root directory and moving the Path code into path (also, polyline, shapes, util, etc)? And all font related stuff into font...

Since `canvas` and `path` are the core of this project, I would rather have them at the root (as you mention, `github.com/tdewolff/canvas/canvas.Canvas` is not nice). Having a lot of files there is does not bother me.

> For HTML Canvas this is necessary due to its different compilation target. 

You should use build tags there (`// +build js`)

> if more renderers are added this may be necessary.

Yes, and having a separate for each renderer can also encourage people to write their own! (inside this module, or their own module)

> We could also put all renderers in a directory called renderers? 

I would prefer having one folder per renderer. The description of the repo says it all: `vector to SVG, PDF, EPS, raster, HTML Canvas, etc. ` => root package is for the `vector` representation, each sub package is for the other side of the `to`.

Moreover, if all renderers are in one package, it does not help for the dependency issue.

---

I would like to give it a try in a MR, but if you don't think that you would merge it, I would prefer not starting it :smiley:

**Comment by tdewolff** [comment]
I like the idea, I think you have a good point! Before you start perhaps we need to think how to solve the `SaveXXX` API regression. Perhaps we could add a `Save` method for each renderer, such as `pdf.Save(c canvas.Canvas, filename string)`? But this kind of defeats the purpose of of canvas really (which is really a Renderer which saves all actions to its buffers). If we put all renderers in separate directories, I feel like `Canvas` should as well as it implements `Renderer` as well. We could rename `Canvas` to prevent stuttering in naming...

Small point, but `canvas/png`, `canvas/jpeg`, `canvas/gif` subpackage names will interfere with the stdlib `image/png` etc. packages. Also `canvas/gonum` would interfere with `gonum` (which both would be needed to be imported for a user that wants to use both).

Overal, I like the idea but we need to fix the `SaveXXX` API regression (I think it is really a nice and easy functionality that ppl are looking for). What is your opinion?

**Comment by oliverpool** [comment]
Taking the `example/preview`:
```go
func main() {
	fontFamily = canvas.NewFontFamily("DejaVu Serif")
	fontFamily.Use(canvas.CommonLigatures)
	if err := fontFamily.LoadLocalFont("DejaVuSerif", canvas.FontRegular); err != nil {
		panic(err)
	}

	c := canvas.New(200, 100)
	ctx := canvas.NewContext(c)
	draw(ctx)

	////////////////

	c.SaveSVG("out.svg")
	c.SavePDF("out.pdf")
	c.SaveEPS("out.eps")
	c.SavePNG("out.png", 3.2)
}
```

The last lines could be replaced by:
```go
       // import "github.com/tdewolff/canvas/{svg,pdf,eps,raster}"
	svg.WriteFile("out.svg", c)
	pdf.WriteFile("out.pdf", c)
	eps.WriteFile("out.eps", c)
	raster.WritePNG("out.png", c, 3.2)
```
_I choose `WriteFile` to mimick [ioutil](https://golang.org/pkg/io/ioutil/#WriteFile)_

For the conflicting package names, there are possibilities:
- find an alternative name (`raster` seems ok for `png`, `jpg`... - could be also `image`)
- let the users use named imports `import canvasGonum "github.com/tdewolff/canvas/gonum"`

In the current case, `gonumplot` seems a better fit.

Another challenge will be `go-chart`, which is not a renderer, but rather an adapter (which allows the `go-chart` to draw an a `canvas.Canvas`.
I would let it as is (just adapting the save method to use the proper sub-package)
```
        graph := ...
	f, _ := os.Create("output.pdf")
	defer f.Close()
	graph.Render(canvas.NewGoChart(canvas.OutputPDF), f)
```

```
        graph := ...
	f, _ := os.Create("output.pdf")
	defer f.Close()
	graph.Render(canvas.NewGoChart(pdf.GoChartWriter), f)
```

I will start a PR, to see how it feels.
