### ISSUE TITLE
Importing into a new package is not currently working because "star-tex" is offline

### ISSUE THREAD

**Issue by carbocation** [tdewolff/canvas#243]
Importing `tdewolff/canvas` into a new library isn't currently functional for me because I am not able to install it due to a dependency failure:

```sh
$ go mod tidy
go: finding module for package github.com/tdewolff/canvas
go: found github.com/tdewolff/canvas in github.com/tdewolff/canvas v0.0.0-20230824220451-8bc6ac4f4d34
go: downloading star-tex.org/x/tex v0.4.0
go: github.com/carbocation/package imports
        github.com/tdewolff/canvas imports
        star-tex.org/x/tex: unrecognized import path "star-tex.org/x/tex": https fetch: Get "https://star-tex.org/x/tex?go-get=1": read tcp 192.168.50.95:55160->213.186.33.5:443: read: connection reset by peer
```

The star-text.org website is rendering a parking page:

<img width="931" alt="image" src="https://github.com/tdewolff/canvas/assets/218804/8ccd8437-e4dc-417e-af49-1f0bb89aaa71">

**Comment by carbocation** [comment]
I can workaround this with the following modification of my go.mod file:

```
replace(
    star-tex.org/x/tex => git.sr.ht/~sbinet/star-tex v0.3.0
)
```

**Comment by tdewolff** [comment]
It works for me, and the package says that `star-tex.org/x/tex` is the canonical path. If this is really wrong, we should contact Sebastian about this.

**Comment by carbocation** [comment]
It still doesn't work for me, but since the replace directive works fine in my program's go.mod, this allows me to use your library even though that canonical import isn't working for me. So we can close this if it's working for you, since it could be a local routing problem in my part of the world.

**Comment by tdewolff** [comment]
I will close this as it is working well from here, if this is still an issue please reopen and we'll contact Sebastian.
