### ISSUE TITLE
RTL texts: Numbers inserted from right to left instead of left to right

### ISSUE THREAD

**Issue by mshafiee** [tdewolff/canvas#244]
I've noticed a bug that emerged from a recent commit. When inserting numbers in texts with a right-to-left (RTL) direction, the numbers are being inserted from right to left instead of from left to right.

## Steps to reproduce
1. Switch to a language that uses RTL text direction (e.g., Persian, Arabic, Hebrew).
2. Insert a number into a text: ‍‍`زبان پارسی ۳۷۸۵۶ سال پیش از زبان کهن‌تر پهلوی آمده است.`

## Expected behavior
The numbers should be inserted from left to right. For example, the number 123 should appear as 123, not as 321.

## Actual behavior
The numbers are being inserted from right to left, for example, inserting the number 123 results in 321.

This bug appears after this commit: https://github.com/tdewolff/canvas/commit/ed85723e0088694316e71e142cce3ee22de8e10d.

Please let me know if you need any more information or if there's a workaround available.

Thank you!

**Comment by tdewolff** [comment]
I've pushed out a fix and did a big refactor of RTL functionality and span positioning. The spaces surrounding RTL should now be improved as well. Please report back how it goes, I'm very interested in improving RTL (and other non-Latin scripts) support!

**Comment by mshafiee** [comment]
Thank you for the update! I appreciate your efforts in enhancing the RTL functionality and addressing the span positioning. I'll test the changes and let you know my findings. It's great to see a commitment towards improving support for RTL and other non-Latin scripts. Cheers!
