### ISSUE TITLE
Single line text in a textbox doesn't return OutlineBounds

### ISSUE THREAD

**Issue by mufty** [tdewolff/canvas#249]
It's because of this https://github.com/tdewolff/canvas/blob/master/text.go#L934

Even a single line text has at least 2 lines filled in. The one actual line is on index 1 not 0. The first item in the slice is just an empty object filled when initializing the Text struct.

**Comment by tdewolff** [comment]
Thanks, that was a bug that sneaked in, should be fixed now.

**Comment by mufty** [comment]
confirmed this is fixed now 👍
