### ISSUE TITLE
Bug Report: Index Out of Range Panic for Empty String in text.go

### ISSUE THREAD

**Issue by mshafiee** [tdewolff/canvas#252]
**Description**:
When the length of the string `s` is `0` at [text.go#L340](https://github.com/tdewolff/canvas/blob/86148644b6c292924c3bead16e2303181f7ebbcf/text.go#L340), it leads to a panic at [text.go#L700](https://github.com/tdewolff/canvas/blob/86148644b6c292924c3bead16e2303181f7ebbcf/text.go#L700) with the error:

```
panic: runtime error: index out of range [0] with length 0
```

**Steps to Reproduce**:
1. Call the relevant function with `s` as an empty string.
2. Observe the panic at the aforementioned line.

**Expected Behavior**:
The code should handle the case of an empty string without panicking, perhaps by skipping processing or providing a relevant error message.

**Actual Behavior**:
The code panics with an index out of range error when given an empty string.

**Possible Solution**:
Add a check for the length of the string `s` and handle it gracefully, either by skipping further processing or returning an error.

**Additional Information**:
None.

**Comment by tdewolff** [comment]
Thanks, this should be fixed now!
