### ISSUE TITLE
Bug Report: Text Alignment Issue for Persian/Arabic Strings with Numbers

### ISSUE THREAD

**Issue by mshafiee** [tdewolff/canvas#253]
**Description:**
When using the function `NewTextBox` with a string `s` that contains Persian or Arabic text combined with numbers, the vertical alignment (`valign`) setting seems to be ignored. Instead, the text always aligns to the left.

**Function Signature:**
```go
func NewTextBox(face *FontFace, s string, width, height float64, halign, valign TextAlign, indent, lineStretch float64) *Text
```

**Steps to reproduce:**
1. Call the `NewTextBox` function with a Persian or Arabic string that contains numbers.
2. Set the `valign` to any value.
3. Observe that the text aligns to the left, regardless of the `valign` setting.

**Expected behavior:**
The text should align according to the specified `valign` value.

**Actual behavior:**
Text always aligns to the left, ignoring the `valign` value.

**Additional notes:**
This issue does not seem to occur with strings that are purely in Persian or Arabic, without numbers.

**Comment by tdewolff** [comment]
Should be fixed now!
