### ISSUE TITLE
Word wrap fail inside a textbox under specific conditions.

### ISSUE THREAD

**Issue by lucky986bb** [tdewolff/canvas#257]
[canvas_test.zip](https://github.com/tdewolff/canvas/files/12843934/canvas_test.zip)

I've attached a simplified isolated scenario where this bug manifests. It produces 2 images with slightly different textbox width being the only difference between them. On the first one you can see the text cluttered together with letter overlap and no space between words on line 7. From what I have seen it appears it can occasionally happen when a specific condition is met (the text would exactly fill the line?) On the second one the exact same draw function is used with the width function arg being 1 px (0.98px) wider. This will result in the text on line 7 being rendered correctly. The same can be achieved by removing a character from the test string etc.. 

![image](https://github.com/tdewolff/canvas/assets/147381874/1369602c-20a4-4c88-b692-090f8cd05747)

Could you please look into fixing this? Thanks.

**Comment by lucky986bb** [comment]
Did some more debugging and here is what we found out. 
We have 3 examples of this happening at hand, the isolated example in the OP being one of them. Tracked the symptom of the issue to the Ratio attribute of breaks in Linebreak function being above 1 and below 2. This happens in all the cases we have seen where the bug manifests. Normally the Ratio gets reset when below -1 or above Tolerance, but that never seems to be the case for values like 1.991 in the case above.
![image](https://github.com/tdewolff/canvas/assets/147381874/f7203aca-0326-4ffd-83d9-08d3d001f445)

We have noticed, that when b.Ratio > 1.0 is added to the condition and as a result the Ratio which is later used to compute the whitespace width and some scaling between words is reset to 0.0 for these values as well then that seems to resolve the issue and the line gets rendered normally:
![image](https://github.com/tdewolff/canvas/assets/147381874/1cf90b58-8510-4e61-889e-2eff967196d8)

Output:
`helvetica_W301.020000.png

Linebreak. Extra ratio reset from 1.991000 on line 7.

helvetica_W302.000000.png`

While this seems to resolve the issue for us in these cases it is probably a very crude and not general enough fix merely curing the symptom and not the cause of the issue. Nontheless it could probably be a hint for you on what to look into.

Note: The issue is not a one-of by any means and occasionally occurs if you render a lot of various multiline text in the texbox element.

**Comment by mufty** [comment]
Yeah this is happening quite a lot it depends on how the text fits within each line. Though we don't really know what the ratio is used for it looks to us like it should be within -1 to +1 range. So resetting it to 0 when it's not does seem to fix it though we ain't sure what other impact that may have. Right now we don't see any with the extensive tests we have on our end.

**Comment by tdewolff** [comment]
Thanks for raising the issue and the in-depth analysis. A ratio of more than 1 should be fine, it simply means that a single space can become three spaces (ratio = 2). It can never be less than -1 though. The algorithm increases the Tolerance every time until all text fits to keep large spaces to a minimum.

The bug however is in the newly refactored code in `ToText`. There are zero-width spaces that can stretch and there are regular spaces that can shrink. For some alignments (specifically, anything but Justify) these spaces are sometimes put next to each other with a penalty (possible line break) in between. Currently, it only shrinks the space but doesn't stretch the zero-width space. I'm working on a fix!

**Comment by tdewolff** [comment]
I've pushed out a fix, please let me know if it works correctly now!

**Comment by mufty** [comment]
I just run our tests first pass looks good will need to do some more testing after thanks ;)

**Comment by lucky986bb** [comment]
I've verified with the tests we have and the bug is gone now. Thanks for the fix.
