### ISSUE TITLE
html and css layout support

### ISSUE THREAD

**Issue by html2any** [tdewolff/canvas#259]
I just wrote a layout engine library with the help of LLM, which is much more efficient for simple HTML than wkhtml: https://github.com/html2any/layout. You can try it
Support flex layout, page split.
The html to image use canvas as render.
The textspliter use sfnt in this project to measure width.
thanks for tdewolff's work

**Comment by tdewolff** [comment]
Thank you for sharing! That is really awesome work, the result looks great. I'm happy to see that this library was of use to you, please share any remarks or bugs so I can keep improving! I've added you to the list of users in the readme.
