### ISSUE TITLE
Inconsistent rendering when using context `SetZIndex()`

### ISSUE THREAD

**Issue by davidjb** [tdewolff/canvas#260]
I'm rendering some paths to a canvas context, and then adding a border/fill behind the items on the canvas. When I invoke the `ctx.SetZIndex(-1)` call, this is where the inconsistency starts - the final image can either be right - and most of the time it is - but some amount of the time (e.g. 16 out of 100 runs), the border isn't drawn and you just get the blue square in the middle.

If I omit the `ctx.SetZIndex(-1)` call, the image is consistent every time, but the border/background rectangle is covering up the previously-drawn content. In this simplified example, I could work around the issue by drawing the blue rectangle _after_ bordered box, but in my actual use case, this isn't possible since I'm fitting the canvas to arbitrary-sized content first and _then_ drawing a border around and background under it (unless I was to duplicate the content rendering and offset its positions etc).

Correct: <img width="25%" alt="image" src="https://github.com/tdewolff/canvas/assets/1002811/36dd9a91-e9f1-455c-a863-f68b698e1d3a">  Incorrect: <img width="10%" alt="image" src="https://github.com/tdewolff/canvas/assets/1002811/d27f1549-312f-462c-9a84-06c568c66358">

```go
package main

import (
	"fmt"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

const borderWidth = 1.0

func main() {
	for i := 0; i < 100; i++ {
		c := canvas.New(100, 100)
		ctx := canvas.NewContext(c)

		// ctx.SetZIndex(0) // has no effect
		ctx.SetFill(canvas.Blue)
		ctx.DrawPath(45, 45, canvas.Rectangle(10, 10))

		border := canvas.Rectangle(c.W+borderWidth*2, c.H+borderWidth*2)
		ctx.SetStroke(canvas.Black)
		ctx.SetStrokeWidth(borderWidth)
		ctx.SetFill(canvas.White)
		ctx.SetZIndex(-1)
		ctx.DrawPath(0, 0, border)

		c.Fit(0.1)

		_ = renderers.Write(fmt.Sprintf("test-%d.png", i), c, canvas.DPMM(6))
	}
}
```

Run in the loop, the results vary. Each run produces different results, suggesting some form of race condition:

<img width="639" alt="image" src="https://github.com/tdewolff/canvas/assets/1002811/eb1c2ec5-706f-496a-8b06-614fdf81a369">

**Comment by tdewolff** [comment]
Thanks for raising this, I've pushed out a fix, let me know if it works!

**Comment by davidjb** [comment]
Amazing, thanks @tdewolff - confirmed it handles the issue. Thanks for the quick fix!
