### ISSUE TITLE
[Question] How to set the background color when drawing font images in PNG format

### ISSUE THREAD

**Issue by shuqingzai** [tdewolff/canvas#261]
## description

What I need is to use the specified font file to write content, the content is the font name, the background color is white, and the picture in PNG format is drawn.

## code

```go
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	drawFontImage()
}

// drawFontImage 画字体图片
func drawFontImage() {
	basePath := "storage/image/"

	// 设置字体
	filename := "DancingScript-Regular"
	fullFilename := filename + ".ttf"
	font := canvas.NewFontFamily(filename)
	if err := font.LoadFontFile(basePath+fullFilename, canvas.FontRegular); err != nil {
		panic(err)
	}
	face := font.Face(40, canvas.Black, canvas.FontRegular, canvas.FontNormal)

	// 创建一个新的画布
	c := canvas.New(300, 300)
	cvsCtx := canvas.NewContext(c)

	// 设置画布背景色
	cvsCtx.SetFillColor(canvas.White)
	cvsCtx.SetStrokeColor(canvas.White)

	// 写入文字
	// 文字容器控制
	text := canvas.NewTextBox(face, filename, 300, 100, canvas.Center, canvas.Justify, 0.0, 0.0)
	cvsCtx.DrawText(0, 150, text)

    // 填充
	cvsCtx.FillStroke()

	// 将画布内容写入到 PNG 图片文件
	outputFilename := basePath + filename + time.Now().Format("2006-02-02_15_04_05") + ".png"
	if err := renderers.Write(outputFilename, c, canvas.DPI(96.0)); err != nil {
		panic(err)
	}
	fmt.Println("文件保存: " + outputFilename)
}
```

## resources

1. font： [Dancing Script](https://fonts.google.com/specimen/Dancing+Script)

## Result

I set a white fill and it doesn't seem to work, I tried other colors too and the same

The PNG format is used, causing the entire image to be transparent. Is there a way to set a white background within the canvas?

```go
cvsCtx.SetFillColor(canvas.White)
cvsCtx.SetStrokeColor(canvas.White)
```

![DancingScript-Regular2023-10-10_12_08_12](https://github.com/tdewolff/canvas/assets/44406033/6d0e6f3c-5944-4d5b-8fd7-021901de517a)

**Comment by tdewolff** [comment]
The `SetFill*` and `SetStroke*` functions set the filling color and stroking color _for the next `DrawPath`_! It is not a drawing operation by itself. Additionally, your call to `FillStroke` doesn't do anything, because you never specified path that should be filled and stroked. The only thing you ever draw is using `DrawText`.

You should use:
```go
ctx.SetFillColor(canvas.White)
ctx.DrawPath(0.0, 0.0, canvas.Rectangle(c.W, c.H))

text := ...
ctx.DrawText(...)
```

And remove the call to `SetStrokeColor` and `FillStroke`.

**Comment by shuqingzai** [comment]
> The `SetFill*` and `SetStroke*` functions set the filling color and stroking color _for the next `DrawPath`_! It is not a drawing operation by itself. Additionally, your call to `FillStroke` doesn't do anything, because you never specified path that should be filled and stroked. The only thing you ever draw is using `DrawText`.
> 
> You should use:
> 
> ```go
> ctx.SetFillColor(canvas.White)
> ctx.DrawPath(0.0, 0.0, canvas.Rectangle(c.W, c.H))
> 
> text := ...
> ctx.DrawText(...)
> ```
> 
> And remove the call to `SetStrokeColor` and `FillStroke`.

@tdewolff 
Thank you, my problem is solved
