### ISSUE TITLE
panic during path intersection calculation

### ISSUE THREAD

**Issue by aldernero** [tdewolff/canvas#272]
Recently while making generative art with Sketchy (which uses canvas), I will occasionally get the following panic:
```bash
panic: runtime error: index out of range [2648] with length 2648

goroutine 1 [running]:
github.com/tdewolff/canvas.(*Path).Settle(0xc000012ab0, 0x2)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/path_intersection.go:208 +0x16f5
github.com/tdewolff/canvas.(*Path).Stroke(0x6?, 0x3fd0000000000000, {0x75a2e0?, 0x9d3fe0?}, {0x75a300?, 0x97fd20?}, 0x6?)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/path_stroke.go:626 +0x22f
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0xc0001f6150, 0x800?, {{{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/renderers/rasterizer/rasterizer.go:84 +0x2ea
github.com/tdewolff/canvas.(*Canvas).RenderViewTo(0xc00007e460, {0x75b888, 0xc0001f6150}, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}})
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/canvas.go:847 +0x3d5
github.com/tdewolff/canvas.(*Canvas).RenderTo(...)
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/canvas.go:832
github.com/tdewolff/canvas/renderers/rasterizer.Draw(0xc00007e460, 0x400e3c78f1e3c78f, {0x75ae40, 0x9d3fe0})
        /home/vernon/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240115005846-3d69968abe72/renderers/rasterizer/rasterizer.go:17 +0xfb
```

However it's been hard to narrow down exactly what's going on. Here is a minimal example where changing the number of points in a path can lead to a panic or not: `numPoints = 200` will lead to a panic, `numPoints = 100` will not.

```go
package main

import (
	"fmt"
	"github.com/aldernero/gaul"
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
	"github.com/tdewolff/canvas/renderers/rasterizer"
	"math"
)

func main() {
	var W, H float64 = 100, 100
	// Calculate the points for a spiral-like path
	var numPoints = 200 // 200 will lead to panic, 100 is ok
	var dtheta = gaul.Deg2Rad(60.0)
	var scale = 2.0
	var digits = []int{5, 8, 8, 2, 3, 5, 2, 9, 4, 1, 1, 7, 6, 4, 7}
	var points []gaul.Point
	x := W / 2
	y := H / 2
	theta := 0.0
	n := len(digits)
	for i := 0; i < numPoints; i++ {
		k := i % n
		newX := x + scale*float64(digits[k])*math.Cos(theta)
		newY := y + scale*float64(digits[k])*math.Sin(theta)
		points = append(points, gaul.Point{X: x, Y: y})
		x = newX
		y = newY
		theta += dtheta
	}
	// Create a new canvas and draw the path
	cnvs := canvas.New(W, H)
	ctx := canvas.NewContext(cnvs)
	ctx.SetFillColor(canvas.Transparent)
	ctx.SetStrokeColor(canvas.Black)
	ctx.SetStrokeWidth(0.25)
	ctx.MoveTo(points[0].X, points[0].Y)
	for _, point := range points {
		ctx.LineTo(point.X, point.Y)
	}
	ctx.Stroke()
	// Save the canvas as an SVG
	err := renderers.Write("spiral.svg", cnvs)
	if err != nil {
		fmt.Println(err)
	}
	// Sketchy calls the following to rasterize the image before it's displayed
	// to the screen with ebiten. This is the function that sometimes panics.
	rasterizer.Draw(cnvs, canvas.DefaultResolution, canvas.DefaultColorSpace)
}
```

Previously, say maybe 2 months ago and before, I never ran into this problem. I have looked at recent commits to canvas, but I can't tell what changes may be contributing to this scenario. I'll continue digging into this, but figured you may be able to identify the issue faster than me :) .

**Comment by aldernero** [comment]
This is the commit where the panics start: https://github.com/tdewolff/canvas/commit/0f2af02ee9796710fab18d3c16c1532bb73569c6

**Comment by tdewolff** [comment]
Thanks for raising this issue. The path intersection code was completely rewritten some months ago, and the path stroking functionality started using it (replacing the removeInnerBend code which was only working for very simple use cases). This will improve output when e.g. stroking a circle with a half-width larger than the radius of the circle, or at the inner-bend of two Bézier/Arc segments.

Unfortunately, the path intersection code is very complicated and is still not covering all edge cases. I've written unit tests for all edge cases but due to limited time I haven't been able to fix them all. However, panics should never occur and I appreciate all bug reports to sift out the panics. I will try and fix this ASAP, thanks!

**Comment by tdewolff** [comment]
I can reproduce the bug locally as well. Just to understand the code, why would the number of points be larger than 30? It seems to repeat itself after 30, which causes the path to overlap itself multiple times.

This will likely stress-test the intersections code as the path has many many self-intersections (the self-intersections code is new and a bit buggy, the path-intersections code between different paths is older and better tested). I will work on a fix but this may take a while...

**Comment by tdewolff** [comment]
I've fixed the bug but it has been a Pyrrhic victory as it fails three tests. Please test and see if you discover any new bugs. You use-case is greatly trying the limits of path intersections and will likely uncover some more bugs I guess!
