### ISSUE TITLE
Fix basic template example on Getting Started wiki page

### ISSUE THREAD

**Issue by davidjb** [tdewolff/canvas#273]
The example on https://github.com/tdewolff/canvas/wiki/Getting-Started has a number of syntax and functional issues that prevent it from working. This is an updated, working example that can be slotted into the page:

```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	// Create new canvas of dimension 100x100 mm
	c := canvas.New(100, 100)

	// Create a canvas context used to keep drawing state
	ctx := canvas.NewContext(c)

	// Create a triangle path from an SVG path and draw it to the canvas
	triangle, err := canvas.ParseSVGPath("L60 0L30 60z")
	if err != nil {
		panic(err)
	}
	ctx.SetFillColor(canvas.Mediumseagreen)
	ctx.DrawPath(0, 0, triangle)

	// Rasterize the canvas and write to a PNG file with 3.2 dots-per-mm (320x320 px)
	err = renderers.Write("getting-started.png", c, canvas.DPMM(3.2))
	if err != nil {
		panic(err)
	}
}
```

(I'd create a PR but that isn't possible for GitHub wikis)

**Comment by tdewolff** [comment]
Thanks David, I've updated the example. Shouldn't the coordinates of the DrawPath operation remain (20,20) though, lest it'd start in the corner?

**Comment by davidjb** [comment]
Good catch @tdewolff, exactly right. I was using this example as a quick base for testing and left that change.

**Comment by tdewolff** [comment]
Changed that. If you find other holes in the documentation or examples I'd be happy to hear about it. I haven't had time to sift through all of that (or add appropriate unit tests for all code). The project has become somewhat overwhelming hehe.
