### ISSUE TITLE
Simple text with stroke border example

### ISSUE THREAD

**Issue by MarkFullerInflxr** [tdewolff/canvas#276]
Hello, 
Im trying to render text with a solid color border, similar to like the Stroke example in the readme. 

Ive been playing with the style / context and other config. Heres my current attempt with no output and no success. Please let me know what I'm missing from the config.

```golang
func main() {
	c := canvas.New(200, 200)
	ctx := canvas.NewContext(c)

	prohibition := canvas.NewFontFamily("prohibition")
	_ = prohibition.LoadFontFile("ProhibitionTest-Regular.ttf", canvas.FontRegular)
	face := prohibition.Face(51, canvas.Green)

	faceFrontPath, _, _ := face.ToPath("Lorem ipsum")

	ctx.SetStrokeWidth(10)
	ctx.SetStrokeColor(color.RGBA{0, 255, 0, 255})

	ctx.RenderPath(faceFrontPath, canvas.Style{
		Fill: canvas.Paint{
			Color:    color.RGBA{0, 0, 255, 255},
			Gradient: nil,
			Pattern:  nil,
		},
		Stroke:       canvas.Paint{Color: color.RGBA{255, 0, 0, 255}, Gradient: nil, Pattern: nil},
		StrokeWidth:  10,
		StrokeCapper: canvas.SquareCapper{},
		StrokeJoiner: canvas.MiterJoiner{},
		DashOffset:   0,
		Dashes:       nil,
		FillRule:     0,
	}, canvas.Matrix{})

	if err := renderers.Write("getting-started.png", c, canvas.DPMM(10.0)); err != nil {
		panic(err)
	}
}

```

**Comment by tdewolff** [comment]
Hi Mark, thanks for reaching out!

The problem is the use of `canvas.Matrix{}`. The zero value is a transformation matrix of all zeros, which multiplies the path by zero horizontally and vertically, so nothing gets draw. Use `canvas.Identity` instead.

You can improve your code, and I would recommend using the `DrawPath` command instead of the lower-level `RenderPath` command. I would rewrite your example as:

```go
package main

import (
	"image/color"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers"
)

func main() {
	c := canvas.New(200, 200)
	ctx := canvas.NewContext(c)

	prohibition := canvas.NewFontFamily("prohibition")
	if err := prohibition.LoadFontFile("ProhibitionTest-Regular.ttf", canvas.FontRegular); err != nil {
            panic(err) // check error!
}

        pt := 51.0
	face := prohibition.Face(pt)
	p, _, err := face.ToPath("Lorem ipsum")
        if err != nil {
            panic(err) // check error!
        }

        x, y := 100.0, 100.0
	ctx.SetStrokeWidth(10.0)
	ctx.SetStrokeColor(canvas.Green)
	ctx.DrawPath(x, y, p)

	if err := renderers.Write("out.png", c, canvas.DPMM(10.0)); err != nil {
		panic(err)
	}
}
```

**Comment by MarkFullerInflxr** [comment]
Awesome! Thank you! Im not well versed in graphics, this is just a means to an end, so this might be an ignorant question. Playing with some of the configuration Im getting some artifacting/pixelation. 
<img width="961" alt="image" src="https://github.com/tdewolff/canvas/assets/146031164/567f6115-0bab-4974-aac1-952e35b6d401">

Is that a consequence of the ttf file or something else? Is there a way to Make the transition between the border and fill more binary and less... blurry?

**Comment by tdewolff** [comment]
Hey Mark, what happens is that the vector paths (the mathematical definition of the shapes from point to point) gets converted into a raster image (such as your picture) to be possible to show on a computer screen. This is called rasterization and causes diagonal lines to be pixelated.

This isn't a problem gives your pixels are small enough (i.e. high resolution). In your case it looks like your resolution is very low, and then you zoomed in. Try to increase the DPMM value at the end of the code to `40.0` for example. Let me know if that looks better.
