### ISSUE TITLE
Font parsing: bad length for subtable 0

### ISSUE THREAD

**Issue by elwinar** [tdewolff/canvas#279]
Hey.
First, thanks for your work with this repository, I've been very pleased to find a quality canvas library in Go.

Now, I've been trying to load some fonts from FontSquirrel, namely https://www.fontsquirrel.com/fonts/caviar-dreams, and encountered an issue. I also tested it with https://www.fontsquirrel.com/fonts/open-sans to be sure (seems like OpenSans would be very closely watched for errors).

Here is a minimal example of the code that demonstrate the issue:

```
package main

import (
	"log/slog"
	"os"

	"github.com/tdewolff/canvas"
)

func main() {
	logger := slog.Default()
	for _, arg := range os.Args[1:] {
		logger := logger.With("arg", arg)
		font, err := canvas.LoadFontFile(arg, 0)
		if err != nil {
			logger.Error("loading font", "err", err)
			continue
		}
		logger.Info("loaded font", "name", font.Name())
	}
}
```

Here is the output from my terminal:

```
$ bin/font-tester OpenSans-*
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-Bold.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-BoldItalic.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-ExtraBold.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-ExtraBoldItalic.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-Italic.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-Light.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-LightItalic.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-Regular.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-Semibold.ttf err="kern: bad length for subtable 0"
2024/03/01 09:04:50 ERROR loading font arg=OpenSans-SemiboldItalic.ttf err="kern: bad length for subtable 0"
```

Tracking the error to this line here https://github.com/tdewolff/canvas/blob/master/font/sfnt.go#L1202 is easy, but now I'm out of my depth because I don't know anything about fonts. It seems dubious that a font published on FontSquirrel would be corrupted somehow, but I've successfully loaded fonts from other sources (as Google Fonts).

Any pointers would be much appreciated, also I'm willing to submit a PR to implement a fix or support the format if it appear those fonts are legitimate and it's just an obscure feature of TTF.

**Comment by tdewolff** [comment]
Thanks for raising this issue. Upon investigation I found that this is technically a bug in the font files. The subtables can have up to 64k bytes, but the number of kerning pairs requires approx 110k. See a detailed description here: https://github.com/fonttools/fonttools/issues/314#issuecomment-118116527

I suppose could fix this in the specific case where:
 - It is the last subtable
 - Its size satisfies: (pairs*6) modulus 64k == length

**Comment by tdewolff** [comment]
That issue has been fixed now, please let me know how it goes.

The issue with the Caviar fonts is that the kern subtable pairs aren't sorted. Also a case of a bad font not following the specification, but I've added the ability to load such tables anyways.

**Comment by tdewolff** [comment]
See fdb987382b1e9b2fc26756635767fde3282b929e and 94b55b0c5a78daeadf57c81994008d3d3de5b14b
