### ISSUE TITLE
unrecognized font file format

### ISSUE THREAD

**Issue by tcurdt** [tdewolff/canvas#29]
Why is this failing with `unrecognized font file format`?

	font := canvas.NewFontFamily("times")
	font.Use(canvas.CommonLigatures)
	if err := font.LoadLocalFont("Times", canvas.FontRegular); err != nil {
		panic(err)
	}
	face := font.Face(6.0, color.Black, canvas.FontRegular, canvas.FontNormal)

Is this a "fount not found"? How do find which is the correct name? The system lists it as "Times".
This is on macOS.

**Comment by tdewolff** [comment]
That means that the command `fc-match Times` returns a filename that is not a WOFF, WOFF2, TTF, OTF or EOF file format. Can you execute the command and see what file type it returns?

**Comment by tcurdt** [comment]
```
% fc-match Times
Fontconfig warning: ignoring UTF-8: not a valid region tag
Times.ttc: "Times" "Regular"
```

Never heard of ttc before 🤔 

```
fc-match "Times New Roman"
Fontconfig warning: ignoring UTF-8: not a valid region tag
Times New Roman.ttf: "Times New Roman" "Regular"
```

That one worked!

Would be great to add the `fc-match` info to the README.

**Comment by tdewolff** [comment]
Looks like TTC is going to take some effort to parse these fonts. While they are quite similar to a regular TTF (it is a bundle of TTF fonts), we need to select a font in the collection and filter out the outlines.
