### ISSUE TITLE
Preview failing in Mac OS X 

### ISSUE THREAD

**Issue by marek-kuticka** [tdewolff/canvas#290]
https://github.com/tdewolff/canvas/blob/9e99fc2fbc3234d22b7032e3051c0742feeedc1f/preview.go#L156

Hi
Any idea why the svg path cannot be drawn
Thx a lot
Marek

**Comment by tdewolff** [comment]
Not sure. The preview is currently not even compiling here, will need to work on that first.

What do you see instead? Is it missing from the preview, or does it give an error?

**Comment by marek-kuticka** [comment]
Hi

below see full trace of what I get when starting. compile goes well, with no issues.

got MacBook Pro with M1 processor, 14.1.1. Sonoma.

GOROOT=/opt/homebrew/Cellar/go/1.22.2/libexec #gosetup
GOPATH=/Users/marek/go #gosetup
/opt/homebrew/Cellar/go/1.22.2/libexec/bin/go build -o /Users/marek/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_github_com_tdewolff_canvas_examples_gio github.com/tdewolff/canvas/examples/gio #gosetup
/Users/marek/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___go_build_github_com_tdewolff_canvas_examples_gio
panic: runtime error: index out of range [1] with length 1

goroutine 35 [running]:
github.com/tdewolff/canvas.leftmostWindings(0x0, {0x140000c0180, 0x1, 0x1053b7868?}, 0xc00dc1fa2b005a7e, 0x401d86f02d3ed862)
        /Users/marek/devel/canvas/path_intersection.go:81 +0x204
github.com/tdewolff/canvas.(*Path).Settle(0x1400000f080, 0x2)
        /Users/marek/devel/canvas/path_intersection.go:264 +0x60c
github.com/tdewolff/canvas.(*Path).Stroke(0x1400000e858, 0x3fe8000000000000, {0x1053ba318?, 0x105cf9320?}, {0x1053ba378?, 0x105cf9320?}, 0x3f847ae147ae147b)
        /Users/marek/devel/canvas/path_stroke.go:613 +0x198
github.com/tdewolff/canvas/renderers/gio.(*Gio).RenderPath(0x14000159380, 0x1400000e108?, {{{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
        /Users/marek/devel/canvas/renderers/gio/gio.go:137 +0x1a8
github.com/tdewolff/canvas.(*Context).DrawPath(0x14000033a40, 0x405b800000000000, 0x404e000000000000, {0x14000033880, 0x1, 0x0?})
        /Users/marek/devel/canvas/canvas.go:668 +0x874
github.com/tdewolff/canvas.DrawPreviewWithAssets(0x14000033a40, {0x14000480000, 0xc9658, 0xc9659}, {0x1400054a000, 0xafc8c, 0xafc8d}, {0x14000780000, 0x37fc0, 0x37fc1}, ...)
        /Users/marek/devel/canvas/preview.go:169 +0x1aac
github.com/tdewolff/canvas.DrawPreview(0x1400027ba40)
        /Users/marek/devel/canvas/preview.go:47 +0x178
main.loop.func1({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1053ba178, 0x140002840d0}, {0xc17f2aa5e44297c0, 0x88379a4, ...}, ...})
        /Users/marek/devel/canvas/examples/gio/main.go:39 +0x22c
gioui.org/layout.Direction.Layout(0x8, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1053ba178, 0x140002840d0}, {0xc17f2aa5e44297c0, ...}, ...}, ...)
        /Users/marek/go/pkg/mod/gioui.org@v0.3.1/layout/layout.go:196 +0x154
main.loop(0x14000284008)
        /Users/marek/devel/canvas/examples/gio/main.go:36 +0x184
main.main.func1()
        /Users/marek/devel/canvas/examples/gio/main.go:18 +0x2c
created by main.main in goroutine 1
        /Users/marek/devel/canvas/examples/gio/main.go:16 +0x24

Process finished with the exit code 2

**Comment by tdewolff** [comment]
Thanks, that is the same error I get. I will work on a fix!

**Comment by marek-kuticka** [comment]
thx a lot...
is there any documentation to how the SVG path shall look like? when looking at "plain" svg, it asks for M attribute first, as move to, etc... this seems to be some subset. if you had some details/documentation for this, I'd be happy for this.

thx a lot in advance.
Marek

**Comment by tdewolff** [comment]
In SVG if a path starts without a MoveTo command it is assumed to be `M0,0`. You can see how the preview should look like here: https://raw.githubusercontent.com/tdewolff/canvas/master/resources/preview/preview.png

**Comment by tdewolff** [comment]
I've fixed two bugs related to this issue, I can now successfully build the preview. Unfortunately there is another bug that prevents displaying the character 'u' in 'tellus' in the text box, this is however somewhat untested or test-failing code that needs quite a lot of work (and I don't have much time now).

**Comment by tdewolff** [comment]
Actually, that last one seemed to be a bug in calculating whether an open path is CCW or not. Seems fixed (though I'm not 100% sure it's correct)!
