### ISSUE TITLE
SVG Rendering Issues

### ISSUE THREAD

**Issue by mangofeet** [tdewolff/canvas#295]
I have a few more SVG files that are having trouble rendering. I have set up an example repo at https://github.com/mangofeet/canvas-test.

Not sure if this is an actual issue, or just out of the scope of the SVG parser within canvas. If the latter, is there a known SVG lib that anyone knows works well to render the SVG to something else so that canvas can use it?

**Comment by tdewolff** [comment]
Hi mangofeet, I'll be on vacation for a week and will try to respond
in-depth after that. The SVG parser is fairly basic and ad-hoc, but I have
no problem in adding more small ad-hoc solutions in the mean while, if that
means it works for you. You can also propose PR for specific features or
changes if you like! It's only the svg.go file you have to worry about.

**Comment by tdewolff** [comment]
It looks like all three SVGs use clip paths, which is not supported and not trivial to implement. This is unlikely to be implemented anytime soon...

**Comment by mangofeet** [comment]
Makes sense, I ended up just exporting them as images from inkscape and using that instead. Thanks for checking that out.
