### ISSUE TITLE
Different output after upgrading to db7265801182

### ISSUE THREAD

**Issue by farhaven** [tdewolff/canvas#296]
Hi!

I finally found the time to try to upgrade our code base from `3711dfc3bb35` to `d5a04e36ef50`, and while the panics I reported previously (#287) are now fixed, the graphical output is different from before.

We have a feature that creates "pills" (text boxes with rounded corners) around little pieces of text along geographical lines that indicate distance. Those pills are positioned at the halfway point between a line's ends, so their position is derived from GNSS-measured positions (projected through a mercator projection).

It looks like for some degenerate cases, the path settlement code is a bit too zealous, which results in the pills becoming "diamond shaped":

![Rendered with `d5a04e36ef50`](https://github.com/tdewolff/canvas/assets/58208/1dc5f0bf-0814-4612-9b0d-c7a8092a6f00)

Downgrading back to `3711dfc3bb35` fixes the rendering:

![Rendered with `3711dfc3bb35`](https://github.com/tdewolff/canvas/assets/58208/d6adc109-e34a-40a1-8cec-39ad21fc8208)

As you can see in the reproducer (below), this is likely again caused by floating point rounding, and I'm perfectly happy if you say "this is beyond the scope of the package".

The following code reproduces the situation:

```go
package main

import (
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"unsafe"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/rasterizer"
)

type Path struct {
	d []float64
}

func main() {
	ctx := canvas.NewFromSize(canvas.Size{W: 20, H: 20})

	rawPath := Path{
		d: []float64{
			1, 1.4628383922409653, 196.203944279415, 1, 16, 2.0000000000000004,
			2, 1.5707963267948966, 2, 3.4081228372180314, 198.2572022827186,
			16, 2, 3.2964151933327095, 202.39402765733564, 2, 16, 2.0000000000000004,
			2, 1.5707963267948966, 2, 1.2431571900291138, 204.3393121023127, 16, 2,
			-0.19073679251786668, 204.30059233440699, 2, 16, 2.0000000000000004, 2,
			1.5707963267948966, 2, -2.1360212374949326, 202.2473343311034, 16, 2,
			-2.0243135936096106, 198.11050895648634, 2, 16, 2.0000000000000004, 2,
			1.5707963267948966, 2, 0.02894440969398504, 196.16522451150928, 16,
			32, 1.4628383922409653, 196.203944279415, 32,
		},
	}

	// Need to perform dark magic to set the raw path because parsing rounds floats.
	path := (*canvas.Path)(unsafe.Pointer(&rawPath))

	style := canvas.DefaultStyle
	style.Fill = canvas.Paint{Color: color.RGBA{R: 75, G: 175, B: 80, A: 255}}
	ctx.RenderPath(path, style, canvas.Identity.Translate(10, -190))

	resolution := canvas.DPI(300)

	img := image.NewRGBA(image.Rect(
		0, 0,
		int(ctx.W*resolution.DPMM()+0.5), int(ctx.H*resolution.DPMM()+0.5)))
	draw.Draw(img, img.Bounds(), image.NewUniform(color.White), image.Point{}, draw.Over)

	raster := rasterizer.FromImage(img, resolution, canvas.DefaultColorSpace)
	ctx.RenderTo(raster)
	raster.Close()

	err := (&png.Encoder{}).Encode(os.Stdout, img)
	if err != nil {
		panic(err)
	}
}
```

**Comment by farhaven** [comment]
FWIW, workarounds seem to be:

* Run the path through `path = canvas.MustParseSVG(path.ToSVG())`, but that presumably introduces some overhead
* Currently we're doing the Mercator projection with `https://pkg.go.dev/github.com/golang/geo/s2#MercatorProjection` using `1.0` as the length scale. Increasing the scale works as well (because then all involved points will be further apart, so rounding doesn't have such a deep effect), at least for the one test case I looked at. I'll ponder whether that is actually the correct solution here instead of pushing the responsibility into the `canvas` package over the weekend.

**Comment by tdewolff** [comment]
Just a regular old bug, thanks for the detailed issue as always. This was happing when flattening a circular arc with a rotation that is not zero. Rotations have no effect on circular arcs (only on elliptical arcs, ie. radius-x != radius-y), so it's not a common case. The commit should fix it for you.

It's funny that the workarounds seemed to work since it wasn't due to floating point trickery. Was the path you passed above generate by you or was it some output from `canvas`? We should avoid printing with a non-zero rotation when it is circular.

**Comment by farhaven** [comment]
As always, thank you very very much for the quick response :)

It was output from canvas, essentially the result of `canvas.RoundedRectangle` with a transformation matrix that kind of boils down to some translation, a rotation, and then again a translation.

If it helps you, I can build a test case that doesn't hard-code the path but instead uses exported `canvas` APIs to build it?

**Comment by tdewolff** [comment]
Thanks Gregor, happy to keep fixing bugs ;-). I wasn't able to find a test case that produces the circular arcs with rotation you observe. Could you find the original pill-shape and the transformation that is applied?
