### ISSUE TITLE
Add API to set ID on SVG elements

### ISSUE THREAD

**Issue by dwlnetnl** [tdewolff/canvas#3]
At first glance this package does exactly what I’m looking for! One thing for me that it doesn’t do is allowing to assign an ID to a SVG element so it can be referenced from JavaScript for things like animation or highlighting a particular part of the drawing.

It would be great if something could be added that helps the use cases I mentioned.

**Comment by tdewolff** [comment]
Sorry for responding so late, I was on vacation and now got back to a busy schedule at the job! Let me see what can be done to address referencing elements and setting names to objects. In the meanwhile, maybe you can reference the objects use CSS selectors such as `svg > path:nth-of-type(21)` though I admit this is not ideal.
