### ISSUE TITLE
Can I export to buffer or base64 instead saving local file?

### ISSUE THREAD

**Issue by luankefei** [tdewolff/canvas#300]
same as title. thanks

**Comment by tdewolff** [comment]
Sure, see https://pkg.go.dev/github.com/tdewolff/canvas/renderers for an overview of implemented writers. I've also added `Canvas.Write` explicitly, but it's really the same as the implementations of `canvas.Writer` in `renderers/renderers.go`.

**Comment by luankefei** [comment]
> Sure, see https://pkg.go.dev/github.com/tdewolff/canvas/renderers for an overview of implemented writers. I've also added `Canvas.Write` explicitly, but it's really the same as the implementations of `canvas.Writer` in `renderers/renderers.go`.

Sorry, I didn't make myself clear. 
When I call `WriteFile()` or `renderer.Write()` It will writes a file to disk then I can open the file transfer into Base64 format. I wonder if there is a way to create an image in memory and convert it to Base64 without writing it to disk

**Comment by tdewolff** [comment]
Like I mentioned, you can use the functions defined in renderers/ or the new `Canvas.Write` function:

```go
c := ...
b := &bytes.Buffer{}
err := renderers.PNG()(b, c)

// or
c := ...
b := &bytes.Buffer{}
err := c.Write(b, renderers.PNG())
```

I've improved the documentation of those function.

**Comment by luankefei** [comment]
that's cool. thanks alot

**Comment by luankefei** [comment]
that's cool. thanks alot

**Comment by luankefei** [comment]
that's cool. thanks alot

**Comment by luankefei** [comment]
that's cool. thanks alot
