### ISSUE TITLE
Using one canvas in another

### ISSUE THREAD

**Issue by fasmide** [tdewolff/canvas#302]
Is it possible to draw one canvas on top of another? - maybe applying transformations to it in the process

I'm tinkering around with parsing an SVG, which leaves me with a canvas (that renders correctly to PNG), and then I would like to place this onto another canvas's context where the main drawing is done.

**Comment by fasmide** [comment]
I get it - sorry for the noise :) 

```golang
	cLogo, _ := canvas.ParseSVG(...)
	c := canvas.New(float64(200), float64(200))
	ctx := canvas.NewContext(c)
	cLogo.RenderTo(ctx)
```

**Comment by tdewolff** [comment]
Exactly! Good to hear this library is useful to you ;-)
