### ISSUE TITLE
Make AVIF and WEBP optional, even if CGO is enabled

### ISSUE THREAD

**Issue by farhaven** [tdewolff/canvas#305]
Hi!

We're building our binaries with CGO enabled because another dependency forces us to. Since this enables AVIF and WEBP, our code now depends on `libwebp` and `libaom-dev`, which in turn means we need to provide them in our build infrastructure.

Since we don't intend to use either AVIF or WEBP in the foreseeable future, would it be possible to build those formats only if, say, build tags `avif` and `webp` are set?

I can provide a patch if this is something you'd consider. If not, I think the new dependencies should be mentioned in the repo `README` file.

**Comment by tdewolff** [comment]
I've created a new build tag 'formats' to enable those formats!
