### ISSUE TITLE
Bug found in path intersection code

### ISSUE THREAD

**Issue by jococi** [tdewolff/canvas#306]
({41.99999939,-0.007174119785} t={1,2.789135735e-08} dir={89.99021317°,89.99021317°} Tangent) 1 2
Path: len=8 data=M40.354799990125656 -11.640022240397748A42 42 0 0 1 41.99999938728576 -0.007174119798682097A3 3 0 0 1 41.999999431051066 -0.006661682670194152A3 3 0 0 1 35.99999947481637 -0.006149245542051552A36 36 0 0 0 34.58982856296605 -9.977161920336748A3.0000000000000027 3.0000000000000027 0 0 1 34.47231427654585 -10.808592080367248A3.0000000000000027 3.0000000000000027 0 0 1 40.354799990125656 -11.640022240397748z
Intersection 0: seg=(1,2) t=(1,2.789135735e-08) pos=(41.99999939,-0.007174119785) dir=(89.99021317°,89.99021317°) tangent

`
goroutine 1 [running]:
github.com/tdewolff/canvas.pathIntersections(0xc000420198, 0x0, 0x0, 0x0)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/path_intersection_util.go:617 +0x2358
github.com/tdewolff/canvas.(*Path).Settle(0xc0003e9ea8, 0x2)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/path_intersection.go:172 +0x338
github.com/tdewolff/canvas.(*Path).Stroke(0xc000194048, 0x4018000000000000, {0xf81100?, 0x12511e0?}, {0xf810a0?, 0x119db10?}, 0x3fb999999999999a)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/path_stroke.go:611 +0x22f
github.com/tdewolff/canvas/renderers/rasterizer.(*Rasterizer).RenderPath(0xc000023680, 0xc000008918?, {{{0x0, 0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, ...}, ...)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/renderers/rasterizer/rasterizer.go:84 +0x2f5
github.com/tdewolff/canvas.(*Canvas).RenderViewTo(0xc00005e580, {0xf829f0, 0xc000023680}, {{0x3ff0000000000000, 0x0, 0x0}, {0x0, 0x3ff0000000000000, 0x0}})
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/canvas.go:826 +0x377
github.com/tdewolff/canvas.(*Canvas).RenderTo(...)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/canvas.go:811
github.com/tdewolff/canvas/renderers/rasterizer.Draw(0xc00005e580, 0x3ff0000000000000, {0xf81ae0, 0x12511e0})
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/renderers/rasterizer/rasterizer.go:17 +0xef
github.com/tdewolff/canvas/renderers.PNG.func1({0xf80fe0, 0xc00005a4f0}, 0x242?)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/renderers/renderers.go:86 +0x3c
github.com/tdewolff/canvas.(*Canvas).WriteFile(0xc00005e580, {0xc00016ecb8?, 0x0?}, 0xc000023650)
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/canvas.go:851 +0x67
github.com/tdewolff/canvas/renderers.Write({0xc00016ecb8, 0x8}, 0xc00005e580, {0x0, 0x0, 0x0})
	C:/Users/funui/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20240625172516-75e5bbe5291d/renderers/renderers.go:31 +0x2bc`

**Comment by tdewolff** [comment]
This should now be fixed with the new (much improved) implementation, see https://github.com/tdewolff/canvas/wiki/Boolean-operations for more information. Most noteworthy is that all tests now finally work, and that I've already seen an improvement of 20x in speed for a typical path. Please re-open new issues if you encounter bugs.
