### ISSUE TITLE
drawImage has margin

### ISSUE THREAD

**Issue by luankefei** [tdewolff/canvas#32]
Sorry to disturb again.

Today I wrote some testing code, to test ctx.DrawImage.

Here is my code

```
func TestBasicDrawImage(t *testing.T) {
  c := Canvas{canvas.New(750, 750)}
  ctx := canvas.NewContext(c)

  // to draw a red background
  ctx.SetFillColor(color.RGBA{0xff, 0x00, 0x00, 0xff})
  ctx.DrawPath(0, 0, canvas.Rectangle(750, 750))

  // image1 start (-1,-1) trying to fix margin
  head, _ := os.Open("../static/head.jpeg")
  img, _ := jpeg.Decode(head)
  ctx.DrawImage(-1, -1, img, 1)

  // image2 at point(0,0)
  bg, _ := os.Open("../static/background.jpeg")
  bgImg, _ := jpeg.Decode(bg)
  ctx.DrawImage(0, 0, bgImg, 1)

  c.SavePNG("out.png", 1)
}
```

And result is:

![image](https://user-images.githubusercontent.com/7992920/77538834-591a2400-6edb-11ea-9594-cabe7ad4953b.png)

You can see there are little margin at left-bottom corner of screen. 
Maybe I can do something like c.DrawImage(x-5, y-5, 1.0) to fix this, but why ?

And here is my testing image,  if you need.
thanks alot.

https://img.laiye.com/checkinAlbum_20200316083737_htqvLACrln.jpg
https://img.laiye.com/cLvgXicdq4RMvFgMeyiarFciatqCEPrkGudP9N6SceHhmA4Tl2unDvK4rNVCFroJZcfqMnUGvnBeDLaZpDYW0TRl9lxmD47gs70.jpg

**Comment by luankefei** [comment]
sorry, how to fix this ?

**Comment by tdewolff** [comment]
I fixed this in the attached commit. Please update `canvas` and let me know if that fixes it for you.

**Comment by luankefei** [comment]
Yes, I tried the same code. they looks fine now. thanks
