### ISSUE TITLE
Intersections and purpose

### ISSUE THREAD

**Issue by icebird72** [tdewolff/canvas#320]
Hello! I recently started learning golang, before that I had always used c++ mainly for Windows. 
First of all, thank you so much for your great work.
But unfortunately, there were some problems when using the canvas package. 
1. Tested on Windows and WASM. The first and main thing is the operation of Boolean intersections for *canvas.Path (I think it's about the boolean function from path_intersection.go).
My purpose: to trim using the Path of some Rectangle ("more complicated" - RoundRectange, or other more "complex" Path) another "complex" Path. The last Path, for example, is the result of a .ToPath from canvas.FontFace for string with the resulting Bounds obviously larger than the desired Path, and centered.
Naturally, before the call .And, both objects are brought to the new Path using .Flatten(…..) (I tried to use different parameters, but the result is either the same, in terms of the problem, not the quality, or panic). When getting the resulting Path, unfortunately, I get artifacts where they shouldn't be - outside of any of the incoming Paths, which shouldn't happen. I tried splitting the Path of a text string into a slice of Path and processing them with .Or and .Xor, the result has ch
<img width="484" alt="Xnip2024-11-02_22-50-49" src="https://github.com/user-attachments/assets/5d5770a8-a301-4151-b734-ceccedcc020d">
anged, but sometimes similar artifacts also occur. But my purpose is render my text in rendering with some Path. For example, under Windows, when rendering images to crop text, I used PushLayer/PopLayer for d2d, and, unfortunately, I did not find such functionality in your package. Perhaps you can suggest another solution?

2. It was tested only under Windows. Rendering speed.
I was surprised, but rendering a Path with only Fill is 8-10 times faster than rendering only Stroke. I can assume that this is antialiasing, but it is strange that it is 8-10 times.

Thank you, with respect to you and your work,
Dmitry

**Comment by tdewolff** [comment]
This is known and I happen to be working on a new implementation these last weeks. It is nearly complete and would (hopefully) solve all problems (at least all tests will for once be working!). I'll keep you up to date.

**Comment by tdewolff** [comment]
You're in luck as I happen to have fixed all test cases yesterday evening. Could you please test if the artifacts are gone?

Regarding rendering speed, while stroking a path it will apply `Path.Settle` which removes all self-intersections. This used to go as O(n^2) with n the number of segments, but the new implementation should go as O(n log n), which for large paths will make a huge difference. See https://github.com/tdewolff/canvas/wiki/Boolean-operations, but and an anecdote I've seen a 20x improvement in speed already!!!

There is another solution to your case however. You could create an image for the gray rectangle and draw the text to it. Then draw this image onto a bigger image (not using Canvas, but using `image.Draw`). This doesn't need any path intersection code and might be much faster. Given the recent rewrite however should give the correct result in any case (please report if you find bugs).

**Comment by icebird72** [comment]
Yeah! It looks like there are no artifacts! I will continue testing, thank you very much!

And I'll check the rendering speed too!

**Comment by tdewolff** [comment]
Will close for now, please re-open if you encounter issues!
