### ISSUE TITLE
[Question] line breaks in textbox

### ISSUE THREAD

**Issue by zpl-zak** [tdewolff/canvas#325]
Hey,

we've recently updated canvas and have noticed few improvements, however there are still some edge cases (that were also present in older iterations) that we aren't sure about and it feels like the line breaks don't seem to behave correctly.

Here's a demo image:
![D6DMemnHoD](https://github.com/user-attachments/assets/d1dd0401-72a6-4652-ba9a-9138f7b313fd)

To me it feels like the first highlighted sentence could contain a few more words than it does right now. I've tried removing the comma, that does not seem to have any effect at all either. If this works as intended, I'd like to ask for some clarification for why this edge case happens,

Here is an isolated demo with the textbox above being rendered:
[linebreaks.zip](https://github.com/user-attachments/files/17868403/linebreaks.zip)

Note the demo currently uses a fork of your font repo (matches master), because of an issue we've opened just recently: https://github.com/tdewolff/font/issues/5. Otherwise the demo would panic while loading the provided font.

**Comment by tdewolff** [comment]
Thanks for the issue, this should now be fixed!

**Comment by zpl-zak** [comment]
> Yes, but that would undo the change above and the problem of your previous post would reappear, doesn't it? It is true that the commit you reference is a custom addition to the algorithm and is not part of the original, but the original doesn't handle all cases correctly as far as I can see.
> 
> I believe the problem you describe is mostly in combination with literal line breaks. I'll try and reproduce the problem and see if it can be fixed.

True, the change above might still be beneficial in the long run, I have not tested a combo of having this change applied with the custom addition from commit above reverted, maybe there's a wiggle room in there we could work with.

In fact the line breaks do appear to be more natural with the change you made, but sadly the overlap issue prevents us from going that route. I agree, could be a combo of changes causing this issue.

Thank you for looking into it!

**Comment by tdewolff** [comment]
This should now be fixed, I've added tests so that we don't see regressions anymore.
