### ISSUE TITLE
drawImage has size error after image.bounds was modified

### ISSUE THREAD

**Issue by luankefei** [tdewolff/canvas#35]
I'm adding crop feature now, and found a strange case.

At first, here is my code, I used module "github.com/oliamb/cutter"
[@see the doc here, if you need](https://pkg.go.dev/github.com/oliamb/cutter@v0.2.2?tab=doc)

```
croppedImg, _ := cutter.Crop(img, cutter.Config{
	Width:  i.Clip.Width,
	Height: i.Clip.Height,
	Anchor: image.Point{i.Clip.X, i.Clip.Y},
})
img = croppedImg

// omitted some code, it doesn't matter
c.DrawImage(x, y, img, scale)
```

The image size was 430 * 430, I crop it, from startPos(30, 30) to (400, 400). after I doing this, ***img.Bounds()*** will lead to (30,30)-(400,400). this could be reason about the case.

![image](https://user-images.githubusercontent.com/7992920/78850660-50ccf780-7a4a-11ea-8c7e-09bb59e95620.png)

So, I save the image to local. here is anthoer test,if I do this. the img.bounds() will be (0,0)-(370,370), and result is fine.

```
croppedImg, _ := cutter.Crop(img, cutter.Config{
	Width:  i.Clip.Width,
	Height: i.Clip.Height,
	Anchor: image.Point{i.Clip.X, i.Clip.Y},
})
img = croppedImg

f, err := os.Create("test_crop.jpg")
if err != nil {
	panic(err)
}
defer f.Close()
jpeg.Encode(f, img, nil)

// omitted some code, it doesn't matter
c.DrawImage(x, y, img, scale)
```

![image](https://user-images.githubusercontent.com/7992920/78850918-0009ce80-7a4b-11ea-86a0-28935e9208e4.png)

I've tried find reason about this, include try another crop image service from aliyun. but it shows similarity.

Here is some code from module "github.com/oliamb/cutter", I thinks it's normal implementation.

```
func Crop(img image.Image, c Config) (image.Image, error) {
	maxBounds := c.maxBounds(img.Bounds())
	size := c.computeSize(maxBounds, image.Point{c.Width, c.Height})
	cr := c.computedCropArea(img.Bounds(), size)
	cr = img.Bounds().Intersect(cr)

	if c.Options&Copy == Copy {
		return cropWithCopy(img, cr)
	}
	if dImg, ok := img.(subImageSupported); ok {
		return dImg.SubImage(cr), nil
	}
	return cropWithCopy(img, cr)
}
```

Thanks.

**Comment by tdewolff** [comment]
> The image size was 430 * 430, I crop it, from startPos(30, 30) to (400, 400). after I doing this, img.Bounds() will lead to (30,30)-(400,400). this could be reason about the case.

Just a reminder that `400,400` is a coordinate not the size, so the size would be `370x370` in this case, is that right?

Maybe the `Anchor: image.Point{i.Clip.X, i.Clip.Y}` is the point from which it will expand, instead of translation? Can you check what the size is of `img` and whether the `scale` is the same in both cases? Sorry, I don't have a lot of time right now to set up a test case

**Comment by luankefei** [comment]
Yes, I calc scale after doing this crop.

```
croppedImg, _ := cutter.Crop(img, cutter.Config{
	Width:  i.Clip.Width,
	Height: i.Clip.Height,
	Anchor: image.Point{30, 30},
})
img = croppedImg

scale := (float64(img.Bounds().Dx()) / i.Width) // 2.466666666666667

fmt.Println(img.Bounds().Dx()) // 370
fmt.Println(i.Width) // 150 actual size that I want

c.DrawImage(i.X, i.Y, img, scale)
```

just before, I wrote a new test using downloaded images from aliyun oss crop service.

```
func TestCropImage(t *testing.T) {
	c := Canvas{canvas.New(750, 750)}
	ctx := canvas.NewContext(c)

	// to draw a red background
	ctx.SetFillColor(color.RGBA{0xff, 0x00, 0x00, 0xff})
	ctx.DrawPath(0, 0, canvas.Rectangle(750, 750))

	head, _ := os.Open("../static/crop_head.png")
	img, _ := png.Decode(head)
	ctx.DrawImage(0, 0, img, 1)

	qcode, _ := os.Open("../static/crop_qrcode.jpeg")
	qcodeImg, _ := jpeg.Decode(qcode)
	ctx.DrawImage(0, 200, qcodeImg, 1)

	c.SavePNG("test_crop.png", 1)
}
```

![image](https://user-images.githubusercontent.com/7992920/79180090-a125ca00-7e3b-11ea-91a7-863da4dbdf46.png)

![image](https://user-images.githubusercontent.com/7992920/79180119-aedb4f80-7e3b-11ea-8585-476e92e00f96.png)

And the image is here, if you need. hope that. will be helpful.
Thanks alot.

**Comment by oliverpool** [comment]
@luankefei can you check if the fix proposed in #37 is working for you?

**Comment by luankefei** [comment]
> @luankefei can you check if the fix proposed in #37 is working for you?

sorry, I'm new to go. I dont know how to get a unmerged version with go mod.
Could you tell it specifically in detail, and I wil try. thanks

**Comment by oliverpool** [comment]
> sorry, I'm new to go
No problem, good that you asked :smiley: 

You have multiple possibilities :
- **simple and dirty** replace `github.com/tdewolff/canvas` imports in your code with `github.com/oliverpool/canvas` (URL of the fork, where I did the PR)

-----

- **clean, but a bit more complex** use https://github.com/rogpeppe/gohack (don't copy the `#...`)
```bash
gohack get -vcs github.com/tdewolff/canvas # get a local copy of the code, and tell go mod to use it
cd ~/gohack/github.com/tdewolff/canvas      # go to your local copy
git remote add oliverpool git@github.com:oliverpool/canvas # add my fork
git fetch oliverpool # get the latest changes of my fork
git checkout fix_render_image # checkout the changes of my MR
```
You can now try to run your code again.
To remove the `hack`, go to your `go.mod` folder and run `gohack undo github.com/tdewolff/canvas`

**Comment by luankefei** [comment]
Yes I were tryed these command, and change all `github.com/tdewolff/canvas` to `github.com/oliverpool/canvas` in my code
```
go get github.com/oliverpool/canvas`
go mod tidy
```

and it shows

```
go: github.com/oliverpool/canvas@v0.0.0-20200319172159-d36ff6920d40: parsing go.mod:
	module declares its path as: github.com/tdewolff/canvas
	        but was required as: github.com/oliverpool/canvas
```

then I set
```
replace github.com/tdewolff/canvas => github.com/oliverpool/canvas v0.0.0-20200319172159-d36ff6920d40
```

it's not working, could you help

**Comment by oliverpool** [comment]
Sorry, you are right, it can't work (I updated my comment).

Does `go mod edit -replace="github.com/tdewolff/canvas=github.com/oliverpool/canvas@fix_render_image"` work?

**Comment by luankefei** [comment]
sorry, is this you mean?

1. undo replace "tdewolff/canvas" to "oliverpool/canvas"
2. go get github.com/oliverpool/canvas@fix_render_image
3. go mod edit -replace="github.com/tdewolff/canvas=github.com/oliverpool/canvas@fix_render_image"
4. go mod tidy

if I did right, it's still shows. maybe I think I did wrong at 2nd step?

```
go: github.com/oliverpool/canvas@v0.0.0-20200414091838-a81c43fb9787: parsing go.mod:
	module declares its path as: github.com/tdewolff/canvas
	        but was required as: github.com/oliverpool/canvas
```

**Comment by oliverpool** [comment]
Did you also revert all the imports to `github.com/tdewolff/canvas` ?

There should be no reference to `oliverpool` in your code, except for one line in the `go.mod`:
```
replace github.com/tdewolff/canvas => github.com/oliverpool/canvas v0.0.0-20200414091838-a81c43fb9787
```

**Comment by luankefei** [comment]
Yes, I you can see in the screenshots

![image](https://user-images.githubusercontent.com/7992920/79231389-8f264480-7e98-11ea-9d4a-485f54dacff1.png)

and I add this line to `go.mod`

```
replace github.com/tdewolff/canvas => github.com/oliverpool/canvas v0.0.0-20200414091838-a81c43fb9787
```

but when I do `go mod tidy` or `go mod download` and `go test` it still shows the same error.

![image](https://user-images.githubusercontent.com/7992920/79231569-dc0a1b00-7e98-11ea-84b0-9096f64c513a.png)

and here is my `go.mod`

![image](https://user-images.githubusercontent.com/7992920/79231638-f512cc00-7e98-11ea-8a40-2ae2b286cd9f.png)

**Comment by oliverpool** [comment]
You should remove the `github.com/oliverpool/canvas` line in your go.mod (from the `require` section)

**Comment by luankefei** [comment]
Yes, you are right. thanks.
But I got this error, when I run `go test -v`

```
./canvas.go:93:3: c.SavePNG undefined (type Canvas has no field or method SavePNG)
./canvas_test.go:208:3: c.SavePNG undefined (type Canvas has no field or method SavePNG)
```

I think the api `SavePNG` is legacy, I need do some update and tell you the answer later

**Comment by oliverpool** [comment]
Yes, `SavePNG` is legacy, you should now use `c.WriteFile`.

For instance (taken from https://github.com/tdewolff/canvas/blob/master/examples/preview/main.go)
```go
c.WriteFile("out.png", rasterizer.PNGWriter(5.0))
```

**Comment by luankefei** [comment]
I changed `SavePNG` to `WriteFile`, and it works. but unfortunately the issue still there. I will push my code to github, and you can get test code from master branch. I was run `go test -v` at `src/canvas`. maybe this will help.
thanks alot.

[https://github.com/luankefei/golang-canvas](https://github.com/luankefei/golang-canvas)

**Comment by oliverpool** [comment]
Ok, apparently there was another bug as well.

Can you try with the latest version of my fix?
```
replace github.com/tdewolff/canvas => github.com/oliverpool/canvas v0.0.0-20200414143817-2158c3b733b4
```

**Comment by luankefei** [comment]
OK, I did.
And it looks greate ! congretulations and thanks.

![image](https://user-images.githubusercontent.com/7992920/79242722-40cc7200-7ea7-11ea-8153-8484a614d88c.png)
