### ISSUE TITLE
Export properties to move pdf & svg renderers to sub packages

### ISSUE THREAD

**Issue by oliverpool** [tdewolff/canvas#36]
_Following #24 & #25_

The `pdf` and `svg` subpackages are not completely split from the `canvas` package because it misses some exported fields .

For instance on `Text` and its `lines`:
- `text.lines`
- `line.spans` (`ff`, `dx`...)
- `wordBoundary`
- `eofBoundary`

I can start a PR to have a precise overview of what is missing and slowly start refactoring what should be done (following your advice).
Or you can take a look yourself and refactor it all at once.

Anyway, please let me know what is your preferred option

**Comment by tdewolff** [comment]
I was thinking of implementing an iterator in `Text` with a callback which passes all that `svg` and `pdf` need, such as `FontFace`, `dx`, `text`, etc. Automatically split word boundaries when those boundaries are more than a basic space, i.e. when word boundaries are widened we need to draw each word separately. This way we don't need to export too much.

On the other hand we could export everything but that'd pollute the API a bit? What's your opinion?

**Comment by oliverpool** [comment]
> On the other hand we could export everything but that'd pollute the API a bit? What's your opinion?

I think that some "pollution" of the API is unavoidable (to give it more flexibility), but I agree that it should be kept to a minimum.

It seems that the `decos` are used exactly the same way by `svg` & `pdf`: build some slice and render them as `Path` with a given color.
So we could probably add a `text.RenderDeco(r.RenderPath)` method which would call `r.RenderPath` with all the paths and respective colors.

For `textSpan`, I don't see any obvious common code. They seem to use almost all fields (only `width` and `sentenceSpacing` are not used:
```
type textSpan struct {
	ff         FontFace // pdf, svg
	text       string     // pdf, svg
	width      float64 // -
	boundaries []textBoundary // pdf

	dx              float64 // pdf, svg
	sentenceSpacing float64 // -
	wordSpacing     float64 //pdf, svg
	glyphSpacing    float64 //pdf, svg
}
```
If we export the struct and those fields, it could be like `text.EachLine(func(y, []Span))` with a callback.

I will try to start a PR draft, with the `RenderDeco` idea, to see how it works.

What do you think?

**Comment by tdewolff** [comment]
It might be an idea to do the sentence/word/glyph splitting in the Text module, but export `ff => Face`, `text`, `dx` and all three `*Spacing`. Perhaps `width` as well. I'd like to keep the whole `textBoundary` stuff private. For example, SVG needs every text span split on sentences (which is already true at the moment, but perhaps not in the future). PDF needs word splitting but only if the wordSpacing is bigger than a regular space (the latter condition would optimize output size for PDF a bit). Likewise, if a renderer doesn't support glyph spacing, we'd need to split on every glyph. And if a renderer supports extra spacing for sentence ends (and word and glyph spacing), it wouldn't need splitting at all.
