### ISSUE TITLE
Uneven number of pages, corrupts pdf

### ISSUE THREAD

**Issue by DennisRutjes** [tdewolff/canvas#42]
First of all, I like to compliment you on this awesome package!

However, I hit a snag during Multiple PDF page generation (more than 2 that is) the following code should illustrate the issue.

```
        buf := &bytes.Buffer{}
	pdf := canvas.NewPDF(buf, 210, 297)

	pdf.NewPage(210, 297)

	pdf.NewPage(210, 297) // if this is commented out, pdf = ok

	pdf.Close()

	ioutil.WriteFile("out.pdf", buf.Bytes(), 0644) // more then 2 pages corrupts pdf

```

Am I doing something wrong?

**Comment by tdewolff** [comment]
Hey Dennis, thanks! Could you indicate with what PDF viewer you're having problems? For me it seems that `evince`, `qpdf` and Chrome are working fine and are showing three blank pages.

**Comment by DennisRutjes** [comment]
Ah, the mac osx previewer is complaining.

**Comment by tdewolff** [comment]
Could still mean there is a bug or a quirk. Does it throw a useful error?

**Comment by DennisRutjes** [comment]
![image](https://user-images.githubusercontent.com/5212133/80754244-ff86c400-8b2e-11ea-8f94-c0b701787778.png)

**Comment by DennisRutjes** [comment]
Apple Books won't show it either, its an Apple Thingy I guuess

**Comment by DennisRutjes** [comment]
checked with the following results on https://www.datalogics.com/products/pdf-tools/pdf-checker/

`PDF Checker 1.5.0  Copyright 2018-2019 Datalogics, Inc. All Rights Reserved

Thu Apr 30 15:09:33 2020

JSON Profile: everything.json

Input Document: dkkm.pdf

File Size: 1.94 MB

<<=CHECKER_SUMMARY_START=>>
general:born-digital
general:damaged
fonts:uses-fonts-fully-embedded
cleanup:suboptimal-compression
sizeInBytes:2038713
canBeOptimized
<<=CHECKER_SUMMARY_END=>>

Optimization Assessment
    Document can be optimized with PDF Optimizer - see details below

General Results
    Errors:
        Damaged document
    Information:
        Document was born digital.  It was produced from PDF authoring software and so it may contain text, images, tables, forms, and other objects.  These types of PDFs typically do not require OCR.
    Checks Completed:
        born-digital
        claims-pdfa-conformance
        claims-pdfe-conformance
        claims-pdfua-conformance
        claims-pdfvt-conformance
        claims-pdfx-conformance
        contains-owner-password
        contains-signature
        damaged
        image-only
        password-protected
        pdf-v2
        unable-to-open
        xfa-type

Userdata Results
    Errors:
        None
    Information:
        None
    Checks Completed:
        contains-annots
        contains-annots-not-for-printing
        contains-annots-not-for-viewing
        contains-annots-without-normal-appearances
        contains-embedded-files
        contains-metadata
        contains-optional-content
        contains-private-data
        contains-transparency

Fonts Results
    Errors:
        None
    Information:
        Uses fonts fully embedded in document: 
            Tahoma (2 instances)
    Checks Completed:
        fontdescriptor-missing-capheight
        fontdescriptor-missing-fields
        uses-base14fonts-not-embedded
        uses-fonts-fully-embedded
        uses-fonts-not-embedded
    How To Optimize:
            Fully embedded fonts can be subset using PDF Optimizer to save space. (2 instances)

Objects Results
    Errors:
        None
    Information:
        None
    Checks Completed:
        contains-javascript-actions
        contains-thumbnails

Cleanup Results
    Errors:
        None
    Information:
        Contains conservatively compressed streams: 
            Uncompressed: (3 instances)
    Checks Completed:
        suboptimal-compression

Image Results
    Errors:
        None
    Information:
        None
    Checks Completed:
        alternate-images

    Color Images
    Errors:
        None
    Information:
        None
    Checks Completed:
        image-depth
        resolution-too-high
        resolution-too-low
        uses-jpeg2000-compression

    Grayscale Images
    Errors:
        None
    Information:
        None
    Checks Completed:
        resolution-too-high
        resolution-too-low
        uses-jpeg2000-compression

    Monochrome Images
    Errors:
        None
    Information:
        None
    Checks Completed:
        resolution-too-high
        resolution-too-low
        uses-jbig2-compression

`

**Comment by DennisRutjes** [comment]
[out.pdf](https://github.com/tdewolff/canvas/files/4560970/out.pdf)
this is the corrupted example 3 page

**Comment by DennisRutjes** [comment]
fun fact even pages are ok again :-)

**Comment by DennisRutjes** [comment]
> Could still mean there is a bug or a quirk. Does it throw a useful error?

**Comment by tdewolff** [comment]
I've tried `pdfinfo`, `pdftotext` and `qpdf` but they all work well on the PDF. However, running https://www.pdf-online.com/osa/validate.aspx I get

```
The page or page tree node has a missing or invalid "Parent" key.
The value of the key Parent must not be of type stream.
The page or page tree node has a missing or invalid "Parent" key.
The value of the key Parent must not be of type stream.
The page or page tree node has a missing or invalid "Parent" key.
The value of the key Parent must not be of type stream.
The document does not conform to the requested standard.
The document doesn't conform to the PDF reference (missing required entries, wrong value types, etc.).
The document does not conform to the PDF 1.7 standard.
```

Which doesn;t sound good! I'll investigate further...

**Comment by tdewolff** [comment]
Can you let me know if this fixes it for you?

**Comment by DennisRutjes** [comment]
sure did!, now the files are showing also in acrobat reader, cheers and thank you for the swift resolution!
