### ISSUE TITLE
What is the replacement for WriteImage ?

### ISSUE THREAD

**Issue by RadhiFadlillah** [tdewolff/canvas#50]
Hi @tdewolff, thanks for this package. 

I've been using this package for several months and it works perfectly. However, today I have to upgrade an old code, so while I'm on it I also upgrade all of its dependencies.

Unfortunately, when I build the code it failed because `WriteImage` method is not exist anymore. Are there replacement for that method ? I want to render a canvas into `image.Image` so I can modify it further.

Thank you.

**Comment by RadhiFadlillah** [comment]
Sorry, I just found it in the doc.

For folks that want to render canvas into `image.Image`, you can do it by using [`rasterizer.Draw`](https://godoc.org/github.com/tdewolff/canvas/rasterizer#Draw) instead of the old `WriteImage`.

@tdewolff, I found the bug where Go failed to build because [`Mimetype`](https://github.com/tdewolff/canvas/blob/9388a5dbebfa4bcb3e4af898e44ffccd6d9b18e8/font.go#L41) is undefined. I believe it should be `MediaType` instead.

**Comment by wrycode** [comment]
For anyone else who got confused reading this because of the dead link, something like this should work:


```go
import ( 
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/rasterizer"	
	"image"
)

func canvasToImage(c *canvas.Canvas) image.Image {
	var res canvas.Resolution
	res = canvas.Resolution(1.0)
	col := canvas.LinearColorSpace{}
	img := rasterizer.Draw(c, res, col)
	return img
}
```

**Comment by tdewolff** [comment]
Yes thank you! In fact, you can simply call `img := rasterizer.Draw(c, canvas.Resolution(1.0), nil)`. It will pick the linear color space automatically. The resolution depends on your use-case obviously.
