### ISSUE TITLE
[pdf] Add RenderJpeg method

### ISSUE THREAD

**Issue by oliverpool** [tdewolff/canvas#54]
Currently `pdf.RenderImage` decodes and re-encodes the image.

I would prefer to have a way to embed a compressed jpeg without those 2 steps (for performance and pdf-size reason).

Would you accept such a PR ? 
Since the renderers are now completely decoupled from the main package, I could also maintain my own package without issue, if you prefer.

_I am not sure how this could be integrated for other renders, but this question can be solved later._

**Comment by tdewolff** [comment]
Yes I would accept such a PR. In fact, this would also be beneficial for keeping image quality. For instance, converting a JPG => bitmap => JPG incurs extra quality loss by the conversion to JPG.

I think broadly this PR should include this: add an `Image` type (in `image.go`) much like `Path` and `Text`, that probably implements https://golang.org/pkg/image/#Image, and can return the byte content of an arbitrary image (JPG, PNG, ...).

One thing though, are we sure that we can put a raw JPG image and know it complies with `JPXFilter` in PDFs? I mean, if it is a valid JPG, is it always valid content for a `JPXFilter` stream? Thanks for taking this up!

**Comment by oliverpool** [comment]
> For instance, converting a JPG => bitmap => JPG incurs extra quality loss by the conversion to JPG.

This is also a good point!

> add an `Image` type (in image.go)

I will look into this.

> know it complies with `JPXFilter` in PDFs

I have been doing some experiments with `pdfFilterDCT` (`DCTDecode`) and it seems to work fine (but yes, it expects the bytes to be correct, otherwise anything can happen...)
