### ISSUE TITLE
Error with font spacing

### ISSUE THREAD

**Issue by kpym** [tdewolff/canvas#63]
When converting a font to path the spaces between the letters are not respected. 

I think that the [kern displacement](https://github.com/tdewolff/canvas/blob/9388a5dbebfa4bcb3e4af898e44ffccd6d9b18e8/fontface.go#L314-L319) in `func (ff FontFace) ToPath(s string) (*Path, float64)` should be done before to add the glyph to the path.

**Comment by tdewolff** [comment]
This was fixed with the merged PR.
