### ISSUE TITLE
SVG rendering: unescaped character in text box results in invalid SVG.

### ISSUE THREAD

**Issue by clarketus** [tdewolff/canvas#66]
I noticed an issue where if a text box contains a character that needs to be escaped, the character is not escaped and the resulting SVG is invalid and cannot be opened.

If I manually escape the text before passing it into the text box (using html.EscapeString) then the resulting text box is rendered assuming the size of the text is the size of the escaped string, not the original. This means that if the text box has a centered horizontal alignment, then the text is not centered but slightly off to the left of center. 

This may be related to text boxes being absolutely positioned, with the exact position being pre-calculated on the input string assuming the string is exactly what will be displayed to the user. If escaping is required, then escaping would need to happen after the position was calculated. 

EG: with input string "text with &amp;amp; symbol", the text box assumes the string is the size of "text with &amp;amp; symbol", but as this is escaped, the resulting rendered SVG will display "text with &amp; symbol" but positioned as if the string was "text with &amp;amp; symbol".

I think this may be solved by something as simple as swapping this line here:
https://github.com/tdewolff/canvas/blob/d9228b138ea8cc35883332458d5cd1343a405603/svg/renderer.go#L324
With:
```
s = html.EscapeString(s)
```

Let me know if this approach would be an adequate solution? If it is, I could send a pull request that implements this.

In the mean time, I have worked around the issue by escaping text box strings post SVG render using a regex:
```
re := regexp.MustCompile(`(<tspan.*?>)(.*?)(<\/tspan>)`)
out := re.ReplaceAllFunc(renderedSvg, func(s []byte) []byte {
	return []byte(re.ReplaceAllString(string(s), `$1`) +
		html.EscapeString(re.ReplaceAllString(string(s), `$2`)) +
		re.ReplaceAllString(string(s), `$3`))
})
```

Thanks for all the hard work on this library!

**Comment by tdewolff** [comment]
Thanks for the bug report, can I get back to you next week?

**Comment by tdewolff** [comment]
Got back quicker than I thought, thanks for the detailed report. It should be fixed now, please let me know if that works for you.

**Comment by clarketus** [comment]
Great, thank you! I will test that out, but from a glance your PR looks like it should work.
