### ISSUE TITLE
panics when parsing SVG

### ISSUE THREAD

**Issue by ukhobotov** [tdewolff/canvas#67]
I'm trying to parse an svg for rasterizing:

```
    menuSvg := `<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
<defs><style>.cls-1{fill:none;}</style></defs>
<title>menu</title>
<rect x="4" y="6" width="24" height="2"/>
<rect x="4" y="24" width="24" height="2"/>
<rect x="4" y="12" width="24" height="2"/>
<rect x="4" y="18" width="24" height="2"/>
<rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32"/>
</svg>\`

    path := canvas.MustParseSVG(menuSvg)
```
but the code panics with an error:
```
panic: bad path: path should start with command

goroutine 1 [running]:
github.com/tdewolff/canvas.MustParseSVG(...)
        /home/fourthsun/go/src/github.com/tdewolff/canvas/path.go:1378
```
it's nonsense, this path can't be bad, cause I've downloaded it as an icon.
Please fix this bug. Thanks

**Comment by kpym** [comment]
This is not an SVG path. An SVG path looks like "M0 0 L 100 100 ..." and is used in the `d` attribute of the `<path>` comand.
For example you can try `canvas.MustParseSVG("M0 0 L 100 100")` or see the [path_test.go](https://github.com/tdewolff/canvas/blob/2478be0374319c6a86b467fd6af8ddef52fe0117/path_test.go) for other examples.

Please check [this for explanation](https://developer.mozilla.org/fr/docs/Web/SVG/Tutoriel/Paths) what an svg path is.

**Comment by ukhobotov** [comment]
Thanks for explanation!
