### ISSUE TITLE
Support fill patterns and gradients

### ISSUE THREAD

**Issue by tdewolff** [tdewolff/canvas#70]
Besides colors, also support gradients (radial, linear) with multiple colors, and patterns made out of paths (such as stripes). Fun addition would be to add Penrose tiling.

For patterns we need path intersection functionality, to cut the repeating pattern with the path fill boundary.

**Comment by kpym** [comment]
I'm not sure that you need path intersection. In the case of vector formats, the clipping is supported in general, and in the case of raster images this can be done with masking.

**Comment by tdewolff** [comment]
Good point, maybe path intersection isn't needed after all!

**Comment by tdewolff** [comment]
I've incorporated implementing view to work for coordinates as well in the roadmap from where it will be tracked: #74
