### ISSUE TITLE
PDF - text renders ok visually but can't be copied-and-pasted or exported

### ISSUE THREAD

**Issue by uncopied** [tdewolff/canvas#75]
Hi ! 

We use canvas (v0.0.0-20201207185132-8c8081480ed5)
to create documents with barcode-128, QRCode and a bit of text - which we render as SVG for preview and PDF for printing. 

Both work great and print nicely, but for some unknown reason, it's impossible to copy and paste from the PDF document : the text appears as garbage fonts. 

For example, I see text 'Hello world' in the PDF document, but it copies as
 􀇘􀆵􀇶􀇶􀈌􀀃􀉩􀈌􀈲􀇶􀆮􀘫
same with File -> Export as Text

Any clue? Example document below,

[out.pdf](https://github.com/tdewolff/canvas/files/6015791/out.pdf)

Thank you !

**Comment by tdewolff** [comment]
Hi uncopied, yes this is a known bug (or lack of feature) for PDFs. The `ToUnicode` CMAP is needed, which requires parsing TTF fonts manually. This has been fixed in the `develop` branch, which has many other changes as well (`RichText` is still missing though). You could try that in the meanwhile.

**Comment by namsor** [comment]
Great, thank you !

**Comment by tdewolff** [comment]
This is now fixed with the merging of the `develop` branch
