### ISSUE TITLE
PDF output no longer working

### ISSUE THREAD

**Issue by petrm** [tdewolff/canvas#8]
Hi,
during one of the changes after 27/12 PDF output got broken. I still get a file with content, but I can't display it in Chrome or OSX preview anymore. Chrome shows an empty canvas, OSX preview just eats all CPUs and crashes.
Converting the PDF to PS and displaying that output however works.

**Comment by tdewolff** [comment]
Can you check if the latest commit c911478 is working for you? It contains an upstream bugfix. If that doesn't fix it, can you post the source that reproduces the problem?

**Comment by petrm** [comment]
That fixed the output, can open it in Chrome now. The OSX preview still has issues, as well as anything based on mupdf. Evince renders OK.
Also looks like memory usage exploded when creating the pdf.

**Comment by tdewolff** [comment]
There were three subtle bugs in the PDF that Chrome seemed to ignore. Please check if 27357d4 fixes it for you, it opens correctly in MuPDF for me now! Thanks for the report.
