### ISSUE TITLE
Testing Canvas with gonum plot fails with a crash

### ISSUE THREAD

**Issue by chmike** [tdewolff/canvas#80]
I used the code example provided here `https://github.com/tdewolff/canvas/blob/master/examples/gonum-plot/main.go` to save my gonum plot as svg with the canvas renderer. 

This is the stack trace of the crash:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x787c42]

goroutine 1 [running]:
github.com/tdewolff/canvas.(*Context).SetFillColor(0xc00012f9e0, 0x0, 0x0)
	/home/meessen/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20210427001043-15a5ba24926a/canvas.go:253 +0x22
github.com/tdewolff/canvas/renderers.(*GonumPlot).SetColor(0xc0000105e0, 0x0, 0x0)
	/home/meessen/go/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20210427001043-15a5ba24926a/renderers/gonumplot.go:68 +0x45
gonum.org/v1/plot/text.Plain.Draw(0xc00000e030, 0x907b98, 0xc00026a2a0, 0x87650a, 0x5, 0x0, 0x0, 0x878d58, 0xa, 0x876154, ...)
	/home/meessen/go/pkg/mod/gonum.org/v1/plot@v0.9.0/text/plain.go:62 +0x144
gonum.org/v1/plot/vg/draw.(*Canvas).FillText(...)
	/home/meessen/go/pkg/mod/gonum.org/v1/plot@v0.9.0/vg/draw/canvas.go:632
gonum.org/v1/plot.(*Legend).Draw(0xc0001c32f8, 0x907e68, 0xc00026a270, 0x4035400000000000, 0x4038530000000000, 0x4081ffffffffffff, 0x406956c000000000)
	/home/meessen/go/pkg/mod/gonum.org/v1/plot@v0.9.0/legend.go:137 +0x519
gonum.org/v1/plot.(*Plot).Draw(0xc0001c2f00, 0x7f73011d6c78, 0xc0000105e0, 0x0, 0x0, 0x4081ffffffffffff, 0x406b000000000000)
	/home/meessen/go/pkg/mod/gonum.org/v1/plot@v0.9.0/plot.go:174 +0xb3a
main.(*Comptes).MakePlot(0xc00012c990, 0x7ffeeb12a347, 0x1a, 0xc00012c990, 0x0)
	/home/meessen/go/src/etfGraph/graph.go:153 +0x8c5
main.main()
	/home/meessen/go/src/etfGraph/main.go:25 +0x14b
```

I’m using 
-  github.com/tdewolff/canvas v0.0.0-20210427001043-15a5ba24926a
-  gonum.org/v1/plot v0.9.0

It’s the latest version of gonum plot. There might be some changes that are not supported by canvas. 

Here is the source code involving canvas:

```
	//if err := p.Save(8*vg.Inch, 3*vg.Inch, filepath.Join(path, "comptes"+fileExt)); err != nil {
	//	return errors.Wrap(err, "save SVG")
	//}

	// dimension are given in millimeter
	const inchToMillimeter = 25.4
	c := canvas.New(8*inchToMillimeter, 3*inchToMillimeter)
	gonumCanvas := renderers.NewGonumPlot(c)
	p.Draw(gonumCanvas)
	if err := c.WriteFile(filepath.Join(path, "comptes"+fileExt), svg.Writer); err != nil {
		return errors.Wrap(err, "save SVG")
	}

	return nil
```

Line 153 is `p.Draw(gonumCanvas)`. This is the call that crashes. 
It seam that the problem is related to font handling. I tested without changing the plot.DefaultFont, and then setting the Variant to "Sans". Both test crashes when trying to use canvas.
 
There was a recent change in gonum plot with font handling in the latest release.

**Comment by chmike** [comment]
Thank you very much. Your latest version resolves the problem. Very reactive. Thank you very much. 

Unfortunately, the text in the SVG was still not selectable when using thunderbird to view it. Is it a limitation of thundebird (skia?) ?
However, I managed to select text in mails on iOS (iPad).  I’m using Spark. That is a good argument to switch to Canvas. I’ll do it and star it.

**Comment by chmike** [comment]
Oops, I can select text with gonum plots (draw2D?) too on iOS. This is apparently new. It wasn’t possible before.

**Comment by tdewolff** [comment]
You should be able to select text in an SVG, please check if you can in a browser such as Firefox or Google Chrome. It is true that gonum should also generate SVGs with selectable text, it is not using draw2d however.
