### ISSUE TITLE
How to draw a polygon with a hole

### ISSUE THREAD

**Issue by tswr** [tdewolff/canvas#82]
I tried to accomplish the above task with the following code, but it didn't work. Please kindly advise what am I missing?

```go
package main

import (
	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/rasterizer"
)

func main() {
	c := canvas.New(256, 256)
	ctx := canvas.NewContext(c)

	ctx.MoveTo(0, 0)
	ctx.LineTo(256, 0)
	ctx.LineTo(128, 256)
	ctx.Close()

	ctx.MoveTo(10, 10)
	ctx.LineTo(246, 10)
	ctx.LineTo(128, 246)
	ctx.Close()

	ctx.SetFillRule(canvas.EvenOdd)
	ctx.SetFillColor(canvas.Lightblue)
	ctx.SetStrokeColor(canvas.Blue)
	ctx.SetStrokeWidth(0.5)

	ctx.FillStroke()

	c.WriteFile("getting-started.png", rasterizer.PNGWriter(1.0))
}
```

**Comment by tswr** [comment]
Ok, I have figured it out, just draw the inside in another direction. Sorry for bothering.

**Comment by tdewolff** [comment]
No bother at all! The filling of a path is actually determined by the `FillRule` which you can set using `canvas.FillRule = canvas.EvenOdd` or `canvas.FillRule = canvas.NonZero` (the latter is the default). See more at https://pkg.go.dev/github.com/tdewolff/canvas#FillRule. Basically, `NonZero` is direction dependent, while `EvenOdd` is not. Most implementations assume `NonZero`. Be aware that `EvenOdd` is not fully supported by all renderers in all cases yet.
