### ISSUE TITLE
fc-match for mac ?

### ISSUE THREAD

**Issue by gedw99** [tdewolff/canvas#83]
i have a need for supporting outputting in many formats and so this code base looks like the "dogs bollocks" as they say, but when trying the examples on a mac, i kept on hitting the need to have  ``` fc-match ```.

i am on mac. I tried both branches...

```


ex-run-doc:
	# panic: exec: "fc-match": executable file not found in $PATH
	cd $(EX)/document && go run .

ex-run-gio:
	# ! panic: exec: "fc-match": executable file not found in $PATH
	cd $(EX)/gio && $(MAKE) all

ex-run-chart:
	# :)
	cd $(EX)/go-chart && go run .

ex-run-opengl:
	# ! ../../text/fribidi_cgo.go:8:10: fatal error: 'fribidi.h' file not found
	cd $(EX)/opengl && $(MAKE) all

ex-run-map:
	# ! needs "fc-match" exe
	cd $(EX)/map && go run .

```

From my limited googling it looks like fc-match is a Linux only lib, and hence why there is no brew install etc :)

**Comment by tdewolff** [comment]
Yes I agree, we should use something more OS-agnostic. Two alternatives I've found are https://github.com/adrg/sysfont and https://github.com/flopp/go-findfont. I particularly find the `sysfont` one useful. I will look into integrating one of them!

**Comment by tdewolff** [comment]
It seems that `sysfont` is OS-agnostic as well, see its depency https://github.com/adrg/xdg

**Comment by gedw99** [comment]
> It seems that `sysfont` is OS-agnostic as well, see its depency https://github.com/adrg/xdg

Ah I missed that. This is great because it was a better match for canvas font requirements

**Comment by gedw99** [comment]
yep that fixes some of the issues compared to the initial issue line above ..

master branch.

````


ex-run-doc:
	# panic: invalid font data
	cd $(EX)/document && go run .

ex-run-gio:
	# ! panic: invalid font data
	cd $(EX)/gio && $(MAKE) all

ex-run-chart:
	# :)
	cd $(EX)/go-chart && go run .

ex-run-opengl:
	# ! ../../text/fribidi_cgo.go:8:10: fatal error: 'fribidi.h' file not found
	cd $(EX)/opengl && $(MAKE) all

ex-run-map:
	# :)
	cd $(EX)/map && go run .

ex-run-html:
	# :)
	cd $(EX)/html-canvas && $(MAKE) all

````

**Comment by tdewolff** [comment]
The OpenGL example was using the CGO bindings of FriBidi, which you apparently don't have installed. I've reverted the default to the native Go implementation.

As to the invalid font data panics, hopefully the Gio one is fixed, but could you please run the following and send me the font binary file? There seems to be a bug in the font parser for the document example.

```go
package main

import (
	"fmt"

	"github.com/adrg/sysfont"
)

func main() {
	finder := sysfont.NewFinder(&sysfont.FinderOpts{
		Extensions: []string{".ttf", ".otf", ".ttc", ".woff", ".woff2", ".eot"},
	})
	font := finder.Match("NimbusRoman-Regular")
	fmt.Println(font.Filename)
}
```

This prints a file path, can you please send the binary to me somehow?

**Comment by tdewolff** [comment]
Please let me know at least the font name that the script above prints, to be able to reproduce and fix this issue ;-)

**Comment by tdewolff** [comment]
@gedw99 Whenever you have time, please let me know the output of the following script. I'd like to fix this bug! ;-)

```go
package main

import (
	"fmt"

	"github.com/adrg/sysfont"
)

func main() {
	finder := sysfont.NewFinder(&sysfont.FinderOpts{
		Extensions: []string{".ttf", ".otf", ".ttc", ".woff", ".woff2", ".eot"},
	})
	font := finder.Match("NimbusRoman-Regular")
	fmt.Println(font.Filename)
}
```

**Comment by gedw99** [comment]
@tdewolff 

here you go 👍 
```

go mod tidy
go: finding module for package github.com/adrg/sysfont
go: found github.com/adrg/sysfont in github.com/adrg/sysfont v0.1.2
➜  examples git:(main) ✗ go mod tidy
➜  examples git:(main) ✗ go run .
/System/Library/Fonts/Supplemental/Hoefler Text.ttc
➜  examples git:(main) ✗ go version
go version go1.16.4 darwin/amd64

``` 

Looks like it got what it thought was the closed match for my mac  ?

wanted: https://en.wikipedia.org/wiki/Nimbus_Roman_No._9_L

found: https://en.wikipedia.org/wiki/Hoefler_Text

**Comment by gedw99** [comment]
@tdewolff 

i am using tinygo wasm and fair bit these days and figured its worth checking the github.com/adrg/sysfont lib.

In https://github.com/tdewolff/canvas/tree/master/examples/html-canvas, i modified the make file to add:

``` 

all:
	GOARCH=wasm GOOS=js go build -o lib.wasm .
	cp "$$(go env GOROOT)/misc/wasm/wasm_exec.js" .
	go run serve.go

all-tinygo:
	tinygo build -o lib.wasm .

``` 


then:

``` 
make all-tinygo 
tinygo build -o lib.wasm .
# github.com/adrg/xdg
../../../../../../../../../../pkg/mod/github.com/adrg/xdg@v0.3.3/paths_unix.go:18:87: Getuid not declared by package os
../../../../../../../../../../pkg/mod/github.com/adrg/xdg@v0.3.3/utils.go:59:16: MkdirAll not declared by package os
../../../../../../../../../../pkg/mod/github.com/adrg/xdg@v0.3.3/utils.go:59:33: ModeDir not declared by package os
make: *** [all-tinygo] Error 1

```

**Comment by gedw99** [comment]
i raised this https://github.com/tdewolff/canvas/issues/88 so that you can get CI working on all OS's.

I have never sniffed for fonts etc on github ci servers, so dont know how it will behave..

**Comment by tdewolff** [comment]
I've raised the TinyGo issue at https://github.com/adrg/sysfont/issues/7. Let's keep the CI stuff in #88 ;-)

I've fixed some issues in parsing the Hoefler font, but it seems that the Go native HarfBuzz implementation doesn't like TTCs. Using `go build --tags harfbuzz` it works, I'm working on a way of extracting a font from a TTC (easy)

**Comment by gedw99** [comment]
I suspect  that the tinygo compile issues are not really his fault.
The wasm tinygo environment has no OS underneath it with respect to a file system so it might be a bit harsh.

there is a project where a OS layer for golang wasm to compile agai at has been created for running in the browser . I can dig it out.

then there is the WASI OS ( so to speak ) which tinygo ( and rust etc ) support as a standard . I might look into what OS std / primitives it provides .

Wasm is still hard work :)

**Comment by tdewolff** [comment]
I've finalized extracting a font from a collection, it should now all work! If not, please reopen.

PS: see the response from Adrian regarding the TinyGo stuff :-)
