### ISSUE TITLE
Strange png rendering behavior 

### ISSUE THREAD

**Issue by dkononovGm** [tdewolff/canvas#86]
Hi! First of all, thank you for creating this useful drawing tool!

I have stubbed upon one very strange issue. I am trying to draw a contour map by using polylines. The issue appears when I am trying to draw non-filled contours with non-zero stroke width. When I use "polyline.ToPath()" the code works well. When I attempt to smoothen the line by using "polyline.Smoothen()" I see unexpected filled rectangles in the resulting PNG file. And the rectangles have purely random sizes and positions at each next run. At the same time SVG files are correct in both the cases.

Here I attach two PNGs and zipped code. To reproduce the issue you may go to the line 259 in the file "main.go". The code is relatively simple and may be straightforwardly unzipped and built.

![20200930_3_correct](https://user-images.githubusercontent.com/84021403/117816291-0af6ea00-b26f-11eb-8019-0251cfbddccd.png)
![20200930_3_incorrect](https://user-images.githubusercontent.com/84021403/117816350-19dd9c80-b26f-11eb-9bc8-5e11e4a26c9f.png)

Best regards,
Dmitry

**Comment by dkononovGm** [comment]
Hello again! I had a similar idea about the problems with colormaps, but it seems that the problem is different. May you try to start the code with smoothing several times in a row. Sometimes, when I change something in the code and recompile it I get correct PNGs. However, next starts results in those PNGs with glitches. At the same time, when I start the code without smoothing (i.e. with "polyline.ToPath()") all subsequent PNGs are correct.

We are now trying to launch the code under a different OS to check if there is some OS-dependency. I normally use MacOS 10.15.5. I will let you know about the results. I hope you've downloaded the code, since my colleague offers to remove the archive from the initial post.

**Comment by tdewolff** [comment]
I've downloaded your package. I just ran it again and the black rectangles appeared for me as well. This is very peculiar, as that means that rendering is not deterministic. It is possible that this is some numerical error, but it is strange nonetheless. I will investigate the problem and report back to you.

**Comment by dkononovGm** [comment]
Thank you! We've just tested the code under Linux and got absolutely the same behavior, correct PNGs with no smoothing and glitched PNGs with smoothed contours.

**Comment by tdewolff** [comment]
I'm working on it, but I'm pretty busy the coming week so can't promise anything. In the mean time, some paths generated by the contours cause problems for the renderer, it is unclear what causes them. I've singled one out for further analysis.

**Comment by dkononovGm** [comment]
I think there is no rush. I would be great to find the bug even if it takes some time.

**Comment by tdewolff** [comment]
The problem seems to appear in this seemingly innocent looking path:

```go
package main

import (
	"fmt"

	"github.com/tdewolff/canvas"
	"github.com/tdewolff/canvas/renderers/rasterizer"
)

var path = `M985.9649808268126 1161.232756459878C986.2869285054657 1169.0146015445034 987.6244834725696 1177.257811327677 989 1183C990.8157448727096 1190.5799522811838 992.6976385624343 1193.8018226924364 995 1200C997.3023614375657 1206.1981773075636 1000.0251906229716 1215.372661511437 1003 1222`

func main() {
	w := 2000
	h := 2000

	p, err := canvas.ParseSVG(path)
	if err != nil {
		panic(err)
	}

	c := canvas.New(float64(w), float64(h))
	ctx := canvas.NewContext(c)
	ctx.DrawPath(0, 0, p.Stroke(5.0, canvas.ButtCap, canvas.BevelJoin))
	c.Fit(10.0)
	c.WriteFile(fmt.Sprintf("out.png"), rasterizer.PNGWriter(1.0))
}
```

which is the same as drawing the following path:

```
M988.4628440538675 1161.1294157664051L988.610054058531 1163.7754403202387L988.8428179248218 1166.5885882674277L989.1629593974355 1169.536693089536L989.5685310648431 1172.5704913532093L990.0521022467683 1175.6192489516043L990.5987964886564 1178.5878553687285L991.1846827052713 1181.3587105716074L991.4312186816342 1182.4176120519164L992.0195726132725 1184.7155993684296L992.6242177002957 1186.7869907330999L993.2683460703637 1188.7392926900234L993.9967490336006 1190.7224557084155L994.371112411036 1191.6802649643378L996.3664803999383 1196.5943384892403L997.3435408053143 1199.1294734387586L998.3815444308493 1202.0250491425195L998.5094049668467 1202.3927116629825L1001.3438081219083 1210.6981368136203L1003.0876242708475 1215.5683936908567L1004.2784836473611 1218.6269358026539L1005.2806742959069 1220.9760249953038L1005.2807677421221 1220.9762331776742L1000.7192322579441 1223.0237668224734M1000.7192322578779 1223.0237668223258L1000.7191309811094 1223.023541194806L999.6481897498684 1220.5138323082529L998.4044630092462 1217.3199645851787L996.6187894548352 1212.3334345222383L993.7855926222417 1204.031490761262L993.660264991707 1203.6711112487392L992.6564591946857 1200.8705265612414L991.7211186426406 1198.4438287281537L989.7238398434346 1193.5249485909844L989.3293081752578 1192.5154966543705L988.5476409747881 1190.3870012202578L987.8496807830154 1188.2715099231166L987.1970414367564 1186.035899732563L986.5687813183658 1183.5823879480836L986.3080755830066 1182.4626593815965L985.6935926177597 1179.5568625848732L985.1238510642015 1176.463251488051L984.6210596963064 1173.2933516837777L984.1992588041444 1170.138088483732L983.8655746882158 1167.0650856584587L983.6220162163052 1164.1210969193714L983.4671175997578 1161.3360971533507L988.4628440538675 1161.1294157664051z
```

Changing any of the stroke width or changing the path numbers seem to fix the problem, suggesting it is probably a fairly exotic / unstable type of error. My suspicion is that this is a problem in the (external) rasterizer, possible due to precision errors.

**Comment by tdewolff** [comment]
Well as always, most time is spent on the smallest bugs. There was a numerical precision error in joining paths while stroking. This seems to fix it, please let me know how it goes!
