### ISSUE TITLE
CI and github actions

### ISSUE THREAD

**Issue by gedw99** [tdewolff/canvas#88]
SO i was thinking that CI is really needed, and have been using this approach which you might like to use.

Nice explicit make files:
https://github.com/jerson/openpgp-mobile/blob/flatbuffers/Makefile

Git hub actions just calls the same make files:
https://github.com/jerson/openpgp-mobile/tree/flatbuffers/.github/workflows

That gets you the ability to have the same make target run for many platforms ( desktop, mobile, wasm)

Then because you have many examples to CI, you can wrap the calls to the make file targets with a strategy pattern like here:
https://github.com/amplify-edge/main/blob/master/.github/workflows/ci.yml#L17

Please notice down the very bottom how the make file asked for is then called.
- https://github.com/amplify-edge/main/blob/master/.github/workflows/ci.yml#L80

I like this pattern because the same make target is run on your laptop and in CI.  Its less work to maintain and you know that whats happens locally is what happen in github ci. When you change your makefiles and you dont have to change your CI workflow files.

**Comment by tdewolff** [comment]
Sounds like an excellent idea! I don't have much time for the moment, but if you want to give it a start in a PR I'd appreciate it!

**Comment by gedw99** [comment]
@tdewolff would love to but also way out of time...

If i get a break will swing back to this..

**Comment by tdewolff** [comment]
Moved to roadmap.
