### ISSUE TITLE
Why are RGB modified in SetFillColor / SetStrokeColor ?

### ISSUE THREAD

**Issue by rickb777** [tdewolff/canvas#92]
I may have missed something here, but I was puzzled by canvas.go around line 272. There are no unit tests for this yet, so I ran it in a sample application using my debugger.

```go
func (c *Context) SetFillColor(col color.Color) {
	r, g, b, a := col.RGBA()
	if a < r {
		r = a
	}
	if a < g {
		g = a
	}
	if a < b {
		b = a
	}
	c.Style.FillColor = color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), uint8(a >> 8)}
}
```

If I understood correctly, the alpha channel is disjoint from the other channels and maybe this method should just be

```go
func (c *Context) SetFillColor(col color.Color) {
	r, g, b, a := col.RGBA()
	c.Style.FillColor = color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), uint8(a >> 8)}
}
```
and this can be better because often the `col` is already an `RGBA` value, so we can type-assert:

```go
func (c *Context) SetFillColor(col color.Color) {
	if rgba, ok := col.(color.RGBA); ok {
		c.Style.FillColor = rgba
	} else {
		r, g, b, a := col.RGBA()
		c.Style.FillColor = color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), uint8(a >> 8)}
	}
}
```

Also note that the same issue applies to `SetStrokeColor`.

This actually causes a bug: suppose the input color is `color.RGBA{R: 245, G: 245, B: 220, A: 128}`. After calling either of these methods, the resulting color would be `color.RGBA{R: 128, G: 128, B: 128, A: 128}`. The color has changed to a gray.

**Comment by tdewolff** [comment]
Thanks for raising concern! Actually, the `RGBA` method returns an alpha-premultiplied colour, as described in https://golang.org/pkg/image/color/#Color. This means that `color.RGBA{R: 128, G: 128, B: 128, A: 128}` is white and not grey! In your case, `color.RGBA{R: 245, G: 245, B: 220, A: 128}` is an invalid colour and will cause a bug when rendering. The option is to either raise a panic or silently change the colours to something valid. I've opted for the latter, hope that explains the code.

**Comment by rickb777** [comment]
Thanks for the explanation.

Would the type-assertion code below improve things? It would avoid two conversions - assuming it's the correct thing to do.

```go
func (c *Context) SetFillColor(col color.Color) {
	if rgba, ok := col.(color.RGBA); ok {
		c.Style.FillColor = rgba
	} else {
		r, g, b, a := col.RGBA()
		if a < r {
			r = a
		}
		if a < g {
			g = a
		}
		if a < b {
			b = a
		}
		c.Style.FillColor = color.RGBA{uint8(r >> 8), uint8(g >> 8), uint8(b >> 8), uint8(a >> 8)}
	}
}
```

**Comment by tdewolff** [comment]
Unfortunately it does not. The `color.RGBA` is exactly the structure that causes problems, any of its instances may be invalid so that we must check accordingly. The `color.NRGBA` structure is always valid though, but would need a conversion anyway to `color.RGBA`.

**Comment by rickb777** [comment]
OK I see now. I was unfamiliar with the alpha pre-multiplication - i.e. `color.RGBA` in this case. I had incorrectly assumed that the semantics of `color.NRGBA` applied.

Thanks anyway.
