### ISSUE TITLE
Incorrect Document Information Dictionary Keywords

### ISSUE THREAD

**Issue by rickb777** [tdewolff/canvas#94]
It seems that the Document Information Dictionary, at the end of the PDF, needs to have correctly-capitalized keys.

Here is a non-normative reference https://www.oreilly.com/library/view/pdf-explained/9781449321581/ch04.html

There is a bug because `renderers/pdf/writer.go` lines 478-489 uses 

* title instead of Title
* subject instead of Subject
* keywords instead of Keywords
* author instead of Author

so these four fields are present in the PDF but ignored by other PDF processing software.

**Comment by rickb777** [comment]
It may also be useful to be able to set the Creator dictionary item, which got missed out.

**Comment by tdewolff** [comment]
Yes a PR would be great! I'm surprised this was missed, as I passed it through multiple conformance checkers.

**Comment by rickb777** [comment]
See [PR#96](../../pull/96).

**Comment by tdewolff** [comment]
Fixed in #96
